s_umfpack_zi_scale – MSOLV-fortran
s_umfpack_zi_scale Subroutine
9 statements
Source File
public subroutine s_umfpack_zi_scale(Xx, Xz, Bx, Bz, Numeric, status)
Arguments
Type Intent Optional Attributes Name
real(kind=r8), intent(out) :: Xx(*)
real(kind=r8), intent(out) :: Xz(*)
real(kind=r8), intent(in) :: Bx(*)
real(kind=r8), intent(in) :: Bz(*)
type(c_ptr), intent(in), optional :: Numeric
integer, optional :: status
Calls
Contents
None
Call graph
s_umfpack_zi_scale calls umfpack_zi_scale
umfpack_zi_scale calls umfpack_zi_scale, umfpack_ci_scale
umfpack_ci_scale calls c_umfpack_zi_scale