s_umfpack_load_symbolic – MSOLV-fortran
s_umfpack_load_symbolic Subroutine
9 statements
Source File
public subroutine s_umfpack_load_symbolic(Symbolic, filename, status, version)
Arguments
Type Intent Optional Attributes Name
type(c_ptr), intent(in) :: Symbolic
character(len=*), intent(in) :: filename
integer, optional :: status
character(len=*), optional :: version
Calls
Contents
None
Call graph
s_umfpack_load_symbolic calls umfpack_load_symbolic
umfpack_load_symbolic calls umfpack_zi_load_symbolic, umfpack_di_load_symbolic
umfpack_zi_load_symbolic calls c_umfpack_zi_load_symbolic
umfpack_di_load_symbolic calls c_umfpack_di_load_symbolic