solve_syst – MSOLV-fortran
solve_syst Subroutine
31 statements
Source File
public subroutine solve_syst(mat, step)
Note
General hat subroutine that handles the resolution steps:
* ini solver initialization
* ana solver analyzis when it's proposed by the solver
* fac solver factorization
* sol solver solution
* fre solver memory release when it's proposed by the solver
* end solver end
Arguments
Type Intent Optional Attributes Name
type(MAT_SOLV), intent(inout) :: mat
high level system type
character(len=*), intent(in) :: step
'ini'=initialize, 'ana'=analyze, 'fac'=factorize, 'sol'=solve, 'fre'=free memory, 'end'=close solver
Calls
Called by
Contents
Source Code
solve_syst
Source Code
   subroutine solve_syst(mat, step)
   implicit none
   type(MAT_SOLV), intent(inout) :: mat   !! *high level system type*
   character(len=*), intent(in)  :: step  !! *'ini'=initialize, 'ana'=analyze, 'fac'=factorize, 'sol'=solve, 'fre'=free memory, 'end'=close solver*
      if ( index(step, 'ini')/=0 ) then ; call init_solver(     mat) ; return ; endif
      if ( index(step, 'ana')/=0 ) then ; call analyse_solver(  mat) ; return ; endif
      if ( index(step, 'fac')/=0 ) then ; call factorize_solver(mat) ; return ; endif
      if ( index(step, 'sol')/=0 ) then ; call solution_solver( mat) ; return ; endif
      if ( index(step, 'fre')/=0 ) then ; call freefact_solver( mat) ; return ; endif
      if ( index(step, 'end')/=0 ) then ; call close_solver( mat)    ; return ; endif
      stop 'Bad step chosen in SOLVE_SYST'
   return
   endsubroutine solve_syst
Call graph
solve_syst calls solution_solver, factorize_solver, close_solver, freefact_solver, init_solver, analyse_solver
solution_solver calls mpi_finalize, ma48_solve, dmumps, s_umfpack_di_solve, solv_superlu
factorize_solver calls s_umfpack_di_numeric, umfpack_di_free_numeric, ma48_factorize, dmumps
close_solver calls umfpack_di_free_numeric, mpi_finalize, umfpack_di_free_symbolic, ma48_finalize, dmumps, close_superlu, umfpack_di_report_info
freefact_solver calls umfpack_di_free_numeric, free_superlu
init_solver calls init_superlu, mpi_finalize, umfpack_di_report_control, ma48_initialize, dmumps, mpi_init, umfpack_di_defaults
analyse_solver calls prep_superlu, ma48_analyse, dmumps, s_umfpack_di_symbolic
init_superlu calls set_default_options
s_umfpack_di_numeric calls umfpack_di_numeric
umfpack_di_free_numeric calls c_umfpack_di_free_numeric
umfpack_di_free_symbolic calls c_umfpack_di_free_symbolic
umfpack_di_report_control calls c_umfpack_di_report_control
prep_superlu calls dcreate_dense_matrix, dcreate_compcol_matrix
s_umfpack_di_solve calls umfpack_di_solve
close_superlu calls destroy_compcol_matrix, destroy_dense_matrix
solv_superlu calls prep_superlu, destroy_compcol_matrix, dgssvx, destroy_supernode_matrix, statfree, statinit
umfpack_di_defaults calls c_umfpack_di_defaults
s_umfpack_di_symbolic calls umfpack_di_symbolic
umfpack_di_report_info calls c_umfpack_di_report_info
umfpack_di_numeric calls c_umfpack_di_numeric
umfpack_di_symbolic calls c_umfpack_di_symbolic
umfpack_di_solve calls c_umfpack_di_solve
test_solvers calls solve_syst