umf4cfnum_ip – MSOLV-fortran
umf4cfnum_ip Subroutine
7 statements
Source File
public subroutine umf4cfnum_ip(Numeric)
Arguments
Type Intent Optional Attributes Name
integer(kind=ip) :: Numeric
Calls
Called by
Contents
None
Call graph
umf4cfnum_ip calls umfpack_free_numeric
umfpack_free_numeric calls umfpack_zi_free_numeric, umfpack_di_free_numeric
umfpack_zi_free_numeric calls c_umfpack_zi_free_numeric
umfpack_di_free_numeric calls c_umfpack_di_free_numeric
umf4cfnum calls umf4cfnum_ip, umf4cfnum