umf4cfsym_ip – MSOLV-fortran
umf4cfsym_ip Subroutine
7 statements
Source File
public subroutine umf4cfsym_ip(Symbolic)
Arguments
Type Intent Optional Attributes Name
integer(kind=ip) :: Symbolic
Calls
Called by
Contents
None
Call graph
umf4cfsym_ip calls umfpack_free_symbolic
umfpack_free_symbolic calls umfpack_di_free_symbolic, umfpack_zi_free_symbolic
umfpack_di_free_symbolic calls c_umfpack_di_free_symbolic
umfpack_zi_free_symbolic calls c_umfpack_zi_free_symbolic
umf4cfsym calls umf4cfsym_ip, umf4cfsym