umf4snum_ip – MSOLV-fortran
umf4snum_ip Subroutine
10 statements
Source File
public subroutine umf4snum_ip(Numeric, filenum, status)
Arguments
Type Intent Optional Attributes Name
integer(kind=ip) :: Numeric
integer, intent(in) :: filenum
integer, intent(out) :: status
Calls
Called by
Contents
None
Call graph
umf4snum_ip calls umfpack_save_numeric
umfpack_save_numeric calls umfpack_di_save_numeric, umfpack_zi_save_numeric
umfpack_di_save_numeric calls c_umfpack_di_save_numeric
umfpack_zi_save_numeric calls c_umfpack_zi_save_numeric
umf4snum calls umf4snum_ip, umf4snum