umf4znum_ip – MSOLV-fortran
umf4znum_ip Subroutine
11 statements
Source File
public subroutine umf4znum_ip(Ap, Ai, Ax, Az, Symbolic, Numeric, Control, Info)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: Ap(*)
integer, intent(in) :: Ai(*)
real(kind=r8), intent(in) :: Ax(*)
real(kind=r8), intent(in) :: Az(*)
integer(kind=ip) :: Symbolic
integer(kind=ip) :: Numeric
real(kind=r8) :: Control(0:UMFPACK_CONTROL-1)
real(kind=r8) :: Info(0:UMFPACK_INFO-1)
Calls
Called by
Contents
None
Call graph
umf4znum_ip calls s_umfpack_numeric
s_umfpack_numeric calls s_umfpack_zi_numeric, s_umfpack_di_numeric, s_umfpack_ci_numeric
s_umfpack_zi_numeric calls s_umfpack_zi_numeric, s_umfpack_ci_numeric
s_umfpack_di_numeric calls umfpack_di_numeric
s_umfpack_ci_numeric calls umfpack_ci_numeric
umfpack_di_numeric calls c_umfpack_di_numeric
umfpack_ci_numeric calls c_umfpack_zi_numeric
umf4num calls umf4znum_ip, umf4num
umf4znum calls umf4znum_ip, umf4znum