umf4scal_ip – MSOLV-fortran
umf4scal_ip Subroutine
9 statements
Source File
public subroutine umf4scal_ip(x, b, Numeric, status)
Arguments
Type Intent Optional Attributes Name
real(kind=r8), intent(out) :: x(*)
real(kind=r8), intent(in) :: b(*)
integer(kind=ip) :: Numeric
integer, intent(out) :: status
Calls
Called by
Contents
None
Call graph
umf4scal_ip calls umfpack_scale_function
umfpack_scale_function calls umfpack_di_scale, umfpack_zi_scale, umfpack_ci_scale
umfpack_di_scale calls c_umfpack_di_scale
umfpack_zi_scale calls umfpack_zi_scale, umfpack_ci_scale
umfpack_ci_scale calls c_umfpack_zi_scale
umf4scal calls umf4scal_ip, umf4scal