umf4lsym – MSOLV-fortran
umf4lsym Subroutine
8 statements
Source File
public subroutine umf4lsym(Symbolic, filenum, status)
Arguments
Type Intent Optional Attributes Name
type(c_ptr) :: Symbolic
integer, intent(in) :: filenum
integer, intent(out) :: status
Calls
Contents
None
Call graph
umf4lsym calls umfpack_load_symbolic
umfpack_load_symbolic calls umfpack_zi_load_symbolic, umfpack_di_load_symbolic
umfpack_zi_load_symbolic calls c_umfpack_zi_load_symbolic
umfpack_di_load_symbolic calls c_umfpack_di_load_symbolic