umf4zpinf – MSOLV-fortran
umf4zpinf Subroutine
4 statements
Source File
public subroutine umf4zpinf(Control, Info)
Arguments
Type Intent Optional Attributes Name
real(kind=r8) :: Control(0:UMFPACK_CONTROL-1)
real(kind=r8) :: Info(0:UMFPACK_INFO-1)
Calls
Contents
None
Call graph
umf4zpinf calls umfpack_report_info
umfpack_report_info calls umfpack_zi_report_info, umfpack_di_report_info
umfpack_zi_report_info calls c_umfpack_zi_report_info
umfpack_di_report_info calls c_umfpack_di_report_info