umf4cpcon – MSOLV-fortran
umf4cpcon Subroutine
4 statements
Source File
public subroutine umf4cpcon(Control)
Arguments
Type Intent Optional Attributes Name
real(kind=r8) :: Control(0:UMFPACK_CONTROL-1)
Calls
Contents
None
Call graph
umf4cpcon calls umfpack_report_control
umfpack_report_control calls umfpack_di_report_control, umfpack_zi_report_control
umfpack_di_report_control calls c_umfpack_di_report_control
umfpack_zi_report_control calls c_umfpack_zi_report_control