umf4zfnum_ip – MSOLV-fortran
umf4zfnum_ip Subroutine
7 statements
Source File
public subroutine umf4zfnum_ip(Numeric)
Arguments
Type Intent Optional Attributes Name
integer(kind=ip) :: Numeric
Calls
Called by
Contents
None
Call graph
umf4zfnum_ip calls umfpack_free_numeric
umfpack_free_numeric calls umfpack_zi_free_numeric, umfpack_di_free_numeric
umfpack_zi_free_numeric calls c_umfpack_zi_free_numeric
umfpack_di_free_numeric calls c_umfpack_di_free_numeric
umf4zfnum calls umf4zfnum_ip, umf4zfnum