umf4zssym_ip – MSOLV-fortran
umf4zssym_ip Subroutine
10 statements
Source File
public subroutine umf4zssym_ip(Symbolic, filenum, status)
Arguments
Type Intent Optional Attributes Name
integer(kind=ip) :: Symbolic
integer, intent(in) :: filenum
integer, intent(out) :: status
Calls
Called by
Contents
None
Call graph
umf4zssym_ip calls umfpack_save_symbolic
umfpack_save_symbolic calls umfpack_zi_save_symbolic, umfpack_di_save_symbolic
umfpack_zi_save_symbolic calls c_umfpack_zi_save_symbolic
umfpack_di_save_symbolic calls c_umfpack_di_save_symbolic
umf4zssym calls umf4zssym_ip, umf4zssym