umf4zlsym_ip – MSOLV-fortran
umf4zlsym_ip Subroutine
11 statements
Source File
public subroutine umf4zlsym_ip(Symbolic, filenum, status)
Arguments
Type Intent Optional Attributes Name
integer(kind=ip) :: Symbolic
integer, intent(in) :: filenum
integer, intent(out) :: status
Calls
Called by
Contents
None
Call graph
umf4zlsym_ip calls umfpack_load_symbolic
umfpack_load_symbolic calls umfpack_zi_load_symbolic, umfpack_di_load_symbolic
umfpack_zi_load_symbolic calls c_umfpack_zi_load_symbolic
umfpack_di_load_symbolic calls c_umfpack_di_load_symbolic
umf4zlsym calls umf4zlsym_ip, umf4zlsym