umf4sol_ip – MSOLV-fortran
umf4sol_ip Subroutine
13 statements
Source File
public subroutine umf4sol_ip(sys, x, b, Numeric, Control, Info)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: sys
real(kind=r8), intent(out) :: x(*)
real(kind=r8), intent(in) :: b(*)
integer(kind=ip) :: Numeric
real(kind=r8) :: Control(0:UMFPACK_CONTROL-1)
real(kind=r8) :: Info(0:UMFPACK_INFO-1)
Calls
Called by
Contents
None
Call graph
umf4sol_ip calls s_umfpack_solve
s_umfpack_solve calls s_umfpack_di_solve, s_umfpack_ci_solve, s_umfpack_zi_solve
s_umfpack_di_solve calls umfpack_di_solve
s_umfpack_ci_solve calls umfpack_ci_solve
s_umfpack_zi_solve calls s_umfpack_ci_solve, s_umfpack_zi_solve
umfpack_ci_solve calls c_umfpack_zi_solve
umfpack_di_solve calls c_umfpack_di_solve
umf4sol calls umf4sol_ip, umf4sol