umf4csnum_ip – MSOLV-fortran
umf4csnum_ip Subroutine
10 statements
Source File
public subroutine umf4csnum_ip(Numeric, filenum, status)
Arguments
Type Intent Optional Attributes Name
integer(kind=ip) :: Numeric
integer, intent(in) :: filenum
integer, intent(out) :: status
Calls
Called by
Contents
None
Call graph
umf4csnum_ip calls umfpack_save_numeric
umfpack_save_numeric calls umfpack_zi_save_numeric, umfpack_di_save_numeric
umfpack_zi_save_numeric calls c_umfpack_zi_save_numeric
umfpack_di_save_numeric calls c_umfpack_di_save_numeric
umf4csnum calls umf4csnum_ip, umf4csnum