umf4pinf – MSOLV-fortran
umf4pinf Subroutine
4 statements
Source File
public subroutine umf4pinf(Control, Info)
Arguments
Type Intent Optional Attributes Name
real(kind=r8) :: Control(0:UMFPACK_CONTROL-1)
real(kind=r8) :: Info(0:UMFPACK_INFO-1)
Calls
Contents
None
Call graph
umf4pinf calls umfpack_report_info
umfpack_report_info calls umfpack_di_report_info, umfpack_zi_report_info
umfpack_di_report_info calls c_umfpack_di_report_info
umfpack_zi_report_info calls c_umfpack_zi_report_info