umf4lnum_ip – MSOLV-fortran
umf4lnum_ip Subroutine
11 statements
Source File
public subroutine umf4lnum_ip(Numeric, filenum, status)
Arguments
Type Intent Optional Attributes Name
integer(kind=ip) :: Numeric
integer, intent(in) :: filenum
integer, intent(out) :: status
Calls
Called by
Contents
None
Call graph
umf4lnum_ip calls umfpack_load_numeric
umfpack_load_numeric calls umfpack_di_load_numeric, umfpack_zi_load_numeric
umfpack_di_load_numeric calls c_umfpack_di_load_numeric
umfpack_zi_load_numeric calls c_umfpack_zi_load_numeric
umf4lnum calls umf4lnum_ip, umf4lnum