umf4zscal_ip – MSOLV-fortran
umf4zscal_ip Subroutine
9 statements
Source File
public subroutine umf4zscal_ip(x, xz, b, bz, Numeric, status)
Arguments
Type Intent Optional Attributes Name
real(kind=r8), intent(out) :: x(*)
real(kind=r8), intent(out) :: xz(*)
real(kind=r8), intent(in) :: b(*)
real(kind=r8), intent(in) :: bz(*)
integer(kind=ip) :: Numeric
integer, intent(out) :: status
Calls
Called by
Contents
None
Call graph
umf4zscal_ip calls umfpack_scale_function
umfpack_scale_function calls umfpack_di_scale, umfpack_zi_scale, umfpack_ci_scale
umfpack_di_scale calls c_umfpack_di_scale
umfpack_zi_scale calls umfpack_zi_scale, umfpack_ci_scale
umfpack_ci_scale calls c_umfpack_zi_scale
umf4zscal calls umf4zscal_ip, umf4zscal
umf4scal calls umf4zscal_ip, umf4scal