umfpack_di_defaults – MSOLV-fortran
umfpack_di_defaults Subroutine
10 statements
Source File
public subroutine umfpack_di_defaults(Control)
Arguments
Type Intent Optional Attributes Name
real(kind=r8), optional target :: Control(0:UMFPACK_CONTROL-1)
Calls
Called by
Contents
None
Call graph
umfpack_di_defaults calls c_umfpack_di_defaults
init_solver calls umfpack_di_defaults
s_umfpack_di_defaults calls umfpack_di_defaults
umfpack_defaults calls umfpack_di_defaults
s_umfpack_defaults calls umfpack_defaults
umf4zdef calls umfpack_defaults
umf4def calls umfpack_defaults
solve_syst calls init_solver
umf4cdef calls umfpack_defaults
test_solvers calls solve_syst