umfpack_save_symbolic – MSOLV-fortran
umfpack_save_symbolic Function
19 statements
Source File
public function umfpack_save_symbolic(Symbolic, filename, version)
Arguments
Type Intent Optional Attributes Name
type(c_ptr), intent(in) :: Symbolic
character(len=*), intent(in) :: filename
character(len=*), optional :: version
Return Value integer
Calls
Called by
Contents
None
Call graph
umfpack_save_symbolic calls umfpack_zi_save_symbolic, umfpack_di_save_symbolic
umfpack_zi_save_symbolic calls c_umfpack_zi_save_symbolic
umfpack_di_save_symbolic calls c_umfpack_di_save_symbolic
umf4zssym calls umfpack_save_symbolic, umf4zssym_ip, umf4zssym
umf4cssym_ip calls umfpack_save_symbolic
umf4cssym calls umfpack_save_symbolic, umf4cssym_ip, umf4cssym
umf4ssym_ip calls umfpack_save_symbolic
umf4zssym_ip calls umfpack_save_symbolic
umf4ssym calls umfpack_save_symbolic, umf4ssym_ip, umf4ssym
s_umfpack_save_symbolic calls umfpack_save_symbolic