umfpack_ci_scale – MSOLV-fortran
umfpack_ci_scale Function
16 statements
Source File
public function umfpack_ci_scale(Xx, Bx, Numeric)
Arguments
Type Intent Optional Attributes Name
complex(kind=r8), target :: Xx(*)
complex(kind=r8), intent(in), target :: Bx(*)
type(c_ptr), intent(in), optional :: Numeric
Return Value integer
Calls
Called by
Contents
None
Call graph
umfpack_ci_scale calls c_umfpack_zi_scale
s_umfpack_ci_scale calls umfpack_ci_scale
umfpack_scale_function calls umfpack_ci_scale
umfpack_zi_scale calls umfpack_ci_scale, umfpack_zi_scale
umf4cscal_ip calls umfpack_scale_function
s_umfpack_scale calls s_umfpack_ci_scale
s_umfpack_zi_scale calls s_umfpack_ci_scale, s_umfpack_zi_scale
umf4scal_ip calls umfpack_scale_function
umf4scal calls umfpack_scale_function, umf4cscal_ip, umf4scal_ip, umf4zscal_ip, umf4scal
umf4cscal calls umfpack_scale_function, umf4cscal_ip, umf4cscal
umf4zscal_ip calls umfpack_scale_function
umf4zscal calls umfpack_scale_function, umf4cscal_ip, umf4zscal_ip, umf4zscal