umfpack_ci_operator_pCSR – MSOLV-fortran
umfpack_ci_operator_pCSR Function
16 statements
Source File
public function umfpack_ci_operator_pCSR(A, B) result(X)
Arguments
Type Intent Optional Attributes Name
type(pCSR_ci), intent(in) :: A
complex(kind=c_double), intent(in) :: B(*)
Return Value complex(kind=c_double) (size(A%Ap)-1)
Calls
Called by
Contents
None
Call graph
umfpack_ci_operator_pcsr calls s_umfpack_ci_symbolic, umfpack_zi_free_numeric, s_umfpack_ci_numeric, umfpack_zi_free_symbolic, s_umfpack_ci_solve
s_umfpack_ci_symbolic calls umfpack_ci_symbolic
umfpack_zi_free_numeric calls c_umfpack_zi_free_numeric
s_umfpack_ci_numeric calls umfpack_ci_numeric
umfpack_zi_free_symbolic calls c_umfpack_zi_free_symbolic
s_umfpack_ci_solve calls umfpack_ci_solve
umfpack_ci_solve calls c_umfpack_zi_solve
umfpack_ci_numeric calls c_umfpack_zi_numeric
umfpack_ci_symbolic calls c_umfpack_zi_symbolic
operator(.umfpack.) calls umfpack_ci_operator_pcsr