umfpack_di_solve – MSOLV-fortran
umfpack_di_solve Function
49 statements
Source File
public function umfpack_di_solve(sys, Ap, Ai, Ax, X, B, Numeric, Control, Info)
Arguments
Type Intent Optional Attributes Name
integer, intent(in), optional :: sys
integer, intent(in), optional target :: Ap(*)
integer, intent(in), optional target :: Ai(*)
real(kind=r8), intent(in), optional target :: Ax(*)
real(kind=r8), target :: X(*)
real(kind=r8), intent(in), target :: B(*)
type(c_ptr), intent(in), optional :: Numeric
real(kind=r8), optional target :: Control(0:UMFPACK_CONTROL-1)
real(kind=r8), optional target :: Info(0:UMFPACK_INFO-1)
Return Value integer
Calls
Called by
Contents
None
Call graph
umfpack_di_solve calls c_umfpack_di_solve
s_umfpack_di_solve calls umfpack_di_solve
umfpack_solve calls umfpack_di_solve
umfpack_di_operator_csc calls s_umfpack_di_solve
solution_solver calls s_umfpack_di_solve
s_umfpack_solve calls s_umfpack_di_solve
umfpack_di_operator_csr calls s_umfpack_di_solve
umfpack_di_operator_pcsr calls s_umfpack_di_solve
umfpack_di_operator_pcsc calls s_umfpack_di_solve
umf4zsolr_ip calls s_umfpack_solve
umf4csolr calls s_umfpack_solve, umf4csolr_ip, umf4csolr
umf4sol_ip calls s_umfpack_solve
operator(.umfpack.) calls umfpack_di_operator_csc, umfpack_di_operator_csr, umfpack_di_operator_pcsr, umfpack_di_operator_pcsc
umf4sol calls s_umfpack_solve, umf4sol_ip, umf4sol
umf4solr calls s_umfpack_solve, umf4zsolr_ip, umf4csolr_ip, umf4solr_ip, umf4solr
umf4zsolr calls s_umfpack_solve, umf4zsolr_ip, umf4csolr_ip, umf4zsolr
solve_syst calls solution_solver
umf4zsol calls s_umfpack_solve
umf4csolr_ip calls s_umfpack_solve
umf4solr_ip calls s_umfpack_solve
umf4csol calls s_umfpack_solve
test_solvers calls solve_syst