umfpack_defaults – MSOLV-fortran
umfpack_defaults Subroutine
18 statements
Source File
public subroutine umfpack_defaults(Control, version)
Arguments
Type Intent Optional Attributes Name
real(kind=r8), optional :: Control(0:UMFPACK_CONTROL-1)
character(len=*), optional :: version
Calls
Called by
Contents
None
Call graph
umfpack_defaults calls umfpack_di_defaults, umfpack_zi_defaults
umfpack_di_defaults calls c_umfpack_di_defaults
umfpack_zi_defaults calls c_umfpack_zi_defaults
umf4zdef calls umfpack_defaults
s_umfpack_defaults calls umfpack_defaults
umf4def calls umfpack_defaults
umf4cdef calls umfpack_defaults