umfpack_ci_solve – MSOLV-fortran
umfpack_ci_solve Function
52 statements
Source File
public function umfpack_ci_solve(sys, Ap, Ai, Ax, Xx, Bx, Numeric, Control, Info)
Arguments
Type Intent Optional Attributes Name
integer, intent(in), optional :: sys
integer, intent(in), optional target :: Ap(*)
integer, intent(in), optional target :: Ai(*)
complex(kind=r8), intent(in), optional target :: Ax(*)
complex(kind=r8), target :: Xx(*)
complex(kind=r8), intent(in), target :: Bx(*)
type(c_ptr), intent(in), optional :: Numeric
real(kind=r8), optional target :: Control(0:UMFPACK_CONTROL-1)
real(kind=r8), optional target :: Info(0:UMFPACK_INFO-1)
Return Value integer
Calls
Called by
Contents
None
Call graph
umfpack_ci_solve calls c_umfpack_zi_solve
umfpack_zi_solve calls umfpack_ci_solve, umfpack_zi_solve
umfpack_solve calls umfpack_ci_solve
s_umfpack_ci_solve calls umfpack_ci_solve
umf4csol_ip calls s_umfpack_ci_solve
umfpack_ci_operator_pcsc calls s_umfpack_ci_solve
s_umfpack_solve calls s_umfpack_ci_solve
s_umfpack_zi_solve calls s_umfpack_ci_solve, s_umfpack_zi_solve
umfpack_ci_operator_csr calls s_umfpack_ci_solve
umfpack_ci_operator_csc calls s_umfpack_ci_solve
umfpack_ci_operator_pcsr calls s_umfpack_ci_solve
umf4solr_ip calls s_umfpack_solve
umf4csol calls umf4csol_ip, umf4csol, s_umfpack_solve
umf4zsolr calls s_umfpack_solve, umf4csolr_ip, umf4zsolr_ip, umf4zsolr
umf4zsol calls umf4csol_ip, umf4zsol, s_umfpack_solve
umf4sol calls s_umfpack_solve, umf4csol_ip, umf4sol, umf4sol_ip
umf4csolr_ip calls s_umfpack_solve
umf4solr calls s_umfpack_solve, umf4solr_ip, umf4csolr_ip, umf4zsolr_ip, umf4solr
umf4csolr calls s_umfpack_solve, umf4csolr_ip, umf4csolr
operator(.umfpack.) calls umfpack_ci_operator_pcsc, umfpack_ci_operator_csr, umfpack_ci_operator_csc, umfpack_ci_operator_pcsr
umf4zsolr_ip calls s_umfpack_solve
umf4sol_ip calls s_umfpack_solve