umfpack_load_numeric – MSOLV-fortran
umfpack_load_numeric Function
19 statements
Source File
public function umfpack_load_numeric(Numeric, filename, version)
Arguments
Type Intent Optional Attributes Name
type(c_ptr), intent(in) :: Numeric
character(len=*), intent(in) :: filename
character(len=*), optional :: version
Return Value integer
Calls
Called by
Contents
None
Call graph
umfpack_load_numeric calls umfpack_zi_load_numeric, umfpack_di_load_numeric
umfpack_zi_load_numeric calls c_umfpack_zi_load_numeric
umfpack_di_load_numeric calls c_umfpack_di_load_numeric
umf4lnum calls umfpack_load_numeric, umf4lnum_ip, umf4lnum
s_umfpack_load_numeric calls umfpack_load_numeric
umf4clnum_ip calls umfpack_load_numeric
umf4clnum calls umfpack_load_numeric, umf4clnum_ip, umf4clnum
umf4zlnum calls umfpack_load_numeric, umf4zlnum_ip, umf4zlnum
umf4zlnum_ip calls umfpack_load_numeric
umf4lnum_ip calls umfpack_load_numeric