umfpack_di_numeric – MSOLV-fortran
umfpack_di_numeric Function
37 statements
Source File
public function umfpack_di_numeric(Ap, Ai, Ax, Symbolic, Numeric, Control, Info)
Arguments
Type Intent Optional Attributes Name
integer, intent(in), target :: Ap(*)
integer, intent(in), target :: Ai(*)
real(kind=r8), intent(in), target :: Ax(*)
type(c_ptr), intent(in), optional :: Symbolic
type(c_ptr), optional :: Numeric
real(kind=r8), optional target :: Control(0:UMFPACK_CONTROL-1)
real(kind=r8), optional target :: Info(0:UMFPACK_INFO-1)
Return Value integer
Calls
Called by
Contents
None
Call graph
umfpack_di_numeric calls c_umfpack_di_numeric
umfpack_numeric calls umfpack_di_numeric
s_umfpack_di_numeric calls umfpack_di_numeric
umfpack_di_operator_csr calls s_umfpack_di_numeric
s_umfpack_numeric calls s_umfpack_di_numeric
umfpack_di_operator_csc calls s_umfpack_di_numeric
umfpack_di_operator_pcsr calls s_umfpack_di_numeric
umfpack_di_operator_pcsc calls s_umfpack_di_numeric
factorize_solver calls s_umfpack_di_numeric
umf4cnum calls s_umfpack_numeric, umf4cnum_ip, umf4cnum
umf4cnum_ip calls s_umfpack_numeric
umf4znum calls s_umfpack_numeric, umf4cnum_ip, umf4znum_ip, umf4znum
solve_syst calls factorize_solver
umf4num calls s_umfpack_numeric, umf4cnum_ip, umf4znum_ip, umf4num_ip, umf4num
umf4znum_ip calls s_umfpack_numeric
umf4num_ip calls s_umfpack_numeric
operator(.umfpack.) calls umfpack_di_operator_csr, umfpack_di_operator_csc, umfpack_di_operator_pcsr, umfpack_di_operator_pcsc
test_solvers calls solve_syst