umfpack_load_symbolic – MSOLV-fortran
umfpack_load_symbolic Function
19 statements
Source File
public function umfpack_load_symbolic(Symbolic, filename, version)
Arguments
Type Intent Optional Attributes Name
type(c_ptr), intent(in) :: Symbolic
character(len=*), intent(in) :: filename
character(len=*), optional :: version
Return Value integer
Calls
Called by
Contents
None
Call graph
umfpack_load_symbolic calls umfpack_zi_load_symbolic, umfpack_di_load_symbolic
umfpack_zi_load_symbolic calls c_umfpack_zi_load_symbolic
umfpack_di_load_symbolic calls c_umfpack_di_load_symbolic
umf4zlsym_ip calls umfpack_load_symbolic
umf4lsym calls umfpack_load_symbolic, umf4lsym_ip, umf4lsym
umf4clsym calls umfpack_load_symbolic, umf4clsym_ip, umf4clsym
umf4clsym_ip calls umfpack_load_symbolic
umf4zlsym calls umfpack_load_symbolic, umf4zlsym_ip, umf4zlsym
umf4lsym_ip calls umfpack_load_symbolic
s_umfpack_load_symbolic calls umfpack_load_symbolic