umfpack_save_numeric – MSOLV-fortran
umfpack_save_numeric Function
19 statements
Source File
public function umfpack_save_numeric(Numeric, filename, version)
Arguments
Type Intent Optional Attributes Name
type(c_ptr), intent(in) :: Numeric
character(len=*), intent(in) :: filename
character(len=*), optional :: version
Return Value integer
Calls
Called by
Contents
None
Call graph
umfpack_save_numeric calls umfpack_di_save_numeric, umfpack_zi_save_numeric
umfpack_di_save_numeric calls c_umfpack_di_save_numeric
umfpack_zi_save_numeric calls c_umfpack_zi_save_numeric
umf4snum_ip calls umfpack_save_numeric
umf4zsnum calls umfpack_save_numeric, umf4zsnum_ip, umf4zsnum
umf4zsnum_ip calls umfpack_save_numeric
s_umfpack_save_numeric calls umfpack_save_numeric
umf4snum calls umfpack_save_numeric, umf4snum_ip, umf4snum
umf4csnum calls umfpack_save_numeric, umf4csnum_ip, umf4csnum
umf4csnum_ip calls umfpack_save_numeric