umfpack_free_symbolic – MSOLV-fortran
umfpack_free_symbolic Subroutine
24 statements
Source File
public subroutine umfpack_free_symbolic(Symbolic, version)
Arguments
Type Intent Optional Attributes Name
type(c_ptr), optional :: Symbolic
character(len=*), optional :: version
Calls
Called by
Contents
None
Call graph
umfpack_free_symbolic calls umfpack_zi_free_symbolic, umfpack_di_free_symbolic
umfpack_zi_free_symbolic calls c_umfpack_zi_free_symbolic
umfpack_di_free_symbolic calls c_umfpack_di_free_symbolic
umf4fsym calls umfpack_free_symbolic, umf4fsym_ip, umf4fsym
s_umfpack_free_symbolic calls umfpack_free_symbolic
umf4cfsym calls umfpack_free_symbolic, umf4cfsym_ip, umf4cfsym
umf4fsym_ip calls umfpack_free_symbolic
umf4zfsym_ip calls umfpack_free_symbolic
umf4zfsym calls umfpack_free_symbolic, umf4zfsym_ip, umf4zfsym
umf4cfsym_ip calls umfpack_free_symbolic