umfpack_di_operator_CSR – MSOLV-fortran
umfpack_di_operator_CSR Function
16 statements
Source File
public function umfpack_di_operator_CSR(A, B) result(X)
Arguments
Type Intent Optional Attributes Name
type(tCSR_di), intent(in) :: A
real(kind=c_double), intent(in) :: B(*)
Return Value real(kind=c_double) (size(A%Ap)-1)
Calls
Called by
Contents
None
Call graph
umfpack_di_operator_csr calls s_umfpack_di_solve, s_umfpack_di_numeric, umfpack_di_free_numeric, umfpack_di_free_symbolic, s_umfpack_di_symbolic
s_umfpack_di_solve calls umfpack_di_solve
s_umfpack_di_numeric calls umfpack_di_numeric
umfpack_di_free_numeric calls c_umfpack_di_free_numeric
umfpack_di_free_symbolic calls c_umfpack_di_free_symbolic
s_umfpack_di_symbolic calls umfpack_di_symbolic
umfpack_di_symbolic calls c_umfpack_di_symbolic
umfpack_di_numeric calls c_umfpack_di_numeric
umfpack_di_solve calls c_umfpack_di_solve
operator(.umfpack.) calls umfpack_di_operator_csr