umfpack_di_load_symbolic – MSOLV-fortran
umfpack_di_load_symbolic Function
5 statements
Source File
public function umfpack_di_load_symbolic(Symbolic, filename)
Arguments
Type Intent Optional Attributes Name
type(c_ptr), intent(in) :: Symbolic
character(len=*), intent(in) :: filename
Return Value integer
Calls
Called by
Contents
None
Call graph
umfpack_di_load_symbolic calls c_umfpack_di_load_symbolic
umfpack_load_symbolic calls umfpack_di_load_symbolic
s_umfpack_di_load_symbolic calls umfpack_di_load_symbolic
umf4zlsym_ip calls umfpack_load_symbolic
umf4lsym calls umfpack_load_symbolic, umf4lsym_ip, umf4lsym
umf4lsym_ip calls umfpack_load_symbolic
umf4clsym_ip calls umfpack_load_symbolic
umf4zlsym calls umfpack_load_symbolic, umf4zlsym_ip, umf4zlsym
s_umfpack_load_symbolic calls umfpack_load_symbolic
umf4clsym calls umfpack_load_symbolic, umf4clsym_ip, umf4clsym