umfpack_zi_operator_pCSR – MSOLV-fortran
umfpack_zi_operator_pCSR Function
17 statements
Source File
public function umfpack_zi_operator_pCSR(A, B) result(X)
Arguments
Type Intent Optional Attributes Name
type(pCSR_zi), intent(in) :: A
type(pVec_zi), intent(in) :: B
Return Value type(tVec_zi)
Calls
Called by
Contents
None
Call graph
umfpack_zi_operator_pcsr calls s_umfpack_zi_symbolic, umfpack_zi_free_symbolic, umfpack_zi_free_numeric, s_umfpack_zi_numeric, s_umfpack_zi_solve
s_umfpack_zi_symbolic calls s_umfpack_zi_symbolic, s_umfpack_ci_symbolic
umfpack_zi_free_symbolic calls c_umfpack_zi_free_symbolic
umfpack_zi_free_numeric calls c_umfpack_zi_free_numeric
s_umfpack_zi_numeric calls s_umfpack_zi_numeric, s_umfpack_ci_numeric
s_umfpack_zi_solve calls s_umfpack_zi_solve, s_umfpack_ci_solve
s_umfpack_ci_numeric calls umfpack_ci_numeric
s_umfpack_ci_symbolic calls umfpack_ci_symbolic
s_umfpack_ci_solve calls umfpack_ci_solve
umfpack_ci_symbolic calls c_umfpack_zi_symbolic
umfpack_ci_numeric calls c_umfpack_zi_numeric
umfpack_ci_solve calls c_umfpack_zi_solve
operator(.umfpack.) calls umfpack_zi_operator_pcsr