umfpack_di_free_numeric – MSOLV-fortran
umfpack_di_free_numeric Subroutine
15 statements
Source File
public subroutine umfpack_di_free_numeric(Numeric)
Arguments
Type Intent Optional Attributes Name
type(c_ptr), optional :: Numeric
Calls
Called by
Contents
None
Call graph
umfpack_di_free_numeric calls c_umfpack_di_free_numeric
factorize_solver calls umfpack_di_free_numeric
close_solver calls umfpack_di_free_numeric
umfpack_di_operator_csr calls umfpack_di_free_numeric
umfpack_di_operator_pcsc calls umfpack_di_free_numeric
umfpack_free_numeric calls umfpack_di_free_numeric
umfpack_di_operator_pcsr calls umfpack_di_free_numeric
freefact_solver calls umfpack_di_free_numeric
s_umfpack_di_free_numeric calls umfpack_di_free_numeric
umfpack_di_operator_csc calls umfpack_di_free_numeric
umf4zfnum calls umfpack_free_numeric, umf4zfnum_ip, umf4zfnum
s_umfpack_free_numeric calls umfpack_free_numeric
umf4fnum_ip calls umfpack_free_numeric
solve_syst calls factorize_solver, close_solver, freefact_solver
umf4zfnum_ip calls umfpack_free_numeric
umf4cfnum_ip calls umfpack_free_numeric
operator(.umfpack.) calls umfpack_di_operator_csr, umfpack_di_operator_pcsc, umfpack_di_operator_pcsr, umfpack_di_operator_csc
umf4fnum calls umfpack_free_numeric, umf4fnum_ip, umf4fnum
umf4cfnum calls umfpack_free_numeric, umf4cfnum_ip, umf4cfnum
test_solvers calls solve_syst