umfpack_di_report_control – MSOLV-fortran
umfpack_di_report_control Subroutine
15 statements
Source File
public subroutine umfpack_di_report_control(Control)
Uses
iso_fortran_env
Arguments
Type Intent Optional Attributes Name
real(kind=r8), optional target :: Control(0:UMFPACK_CONTROL-1)
Calls
Called by
Contents
None
Call graph
umfpack_di_report_control calls c_umfpack_di_report_control
init_solver calls umfpack_di_report_control
s_umfpack_di_report_control calls umfpack_di_report_control
umfpack_report_control calls umfpack_di_report_control
umf4pcon calls umfpack_report_control
solve_syst calls init_solver
s_umfpack_report_control calls umfpack_report_control
umf4zpcon calls umfpack_report_control
umf4cpcon calls umfpack_report_control
test_solvers calls solve_syst