umfpack_report_info – MSOLV-fortran
umfpack_report_info Subroutine
19 statements
Source File
public subroutine umfpack_report_info(Control, Info, version)
Arguments
Type Intent Optional Attributes Name
real(kind=r8), optional :: Control(0:UMFPACK_CONTROL-1)
real(kind=r8) :: Info(0:UMFPACK_INFO-1)
character(len=*), optional :: version
Calls
Called by
Contents
None
Call graph
umfpack_report_info calls umfpack_di_report_info, umfpack_zi_report_info
umfpack_di_report_info calls c_umfpack_di_report_info
umfpack_zi_report_info calls c_umfpack_zi_report_info
umf4pinf calls umfpack_report_info
umf4zpinf calls umfpack_report_info
s_umfpack_report_info calls umfpack_report_info
umf4cpinf calls umfpack_report_info