umfpack_free_numeric – MSOLV-fortran
umfpack_free_numeric Subroutine
24 statements
Source File
public subroutine umfpack_free_numeric(Numeric, version)
Arguments
Type Intent Optional Attributes Name
type(c_ptr), optional :: Numeric
character(len=*), optional :: version
Calls
Called by
Contents
None
Call graph
umfpack_free_numeric calls umfpack_zi_free_numeric, umfpack_di_free_numeric
umfpack_zi_free_numeric calls c_umfpack_zi_free_numeric
umfpack_di_free_numeric calls c_umfpack_di_free_numeric
umf4zfnum calls umfpack_free_numeric, umf4zfnum_ip, umf4zfnum
s_umfpack_free_numeric calls umfpack_free_numeric
umf4fnum_ip calls umfpack_free_numeric
umf4cfnum calls umfpack_free_numeric, umf4cfnum_ip, umf4cfnum
umf4cfnum_ip calls umfpack_free_numeric
umf4fnum calls umfpack_free_numeric, umf4fnum_ip, umf4fnum
umf4zfnum_ip calls umfpack_free_numeric