umfpack_di_scale – MSOLV-fortran
umfpack_di_scale Function
14 statements
Source File
public function umfpack_di_scale(X, B, Numeric)
Arguments
Type Intent Optional Attributes Name
real(kind=r8), target :: X(*)
real(kind=r8), intent(in), target :: B(*)
type(c_ptr), intent(in), optional :: Numeric
Return Value integer
Calls
Called by
Contents
None
Call graph
umfpack_di_scale calls c_umfpack_di_scale
s_umfpack_di_scale calls umfpack_di_scale
umfpack_scale_function calls umfpack_di_scale
umf4cscal calls umfpack_scale_function, umf4cscal_ip, umf4cscal
umf4scal calls umfpack_scale_function, umf4cscal_ip, umf4zscal_ip, umf4scal_ip, umf4scal
umf4zscal calls umfpack_scale_function, umf4cscal_ip, umf4zscal_ip, umf4zscal
umf4cscal_ip calls umfpack_scale_function
s_umfpack_scale calls s_umfpack_di_scale
umf4zscal_ip calls umfpack_scale_function
umf4scal_ip calls umfpack_scale_function