umfpack_di_symbolic – MSOLV-fortran
umfpack_di_symbolic Function
39 statements
Source File
public function umfpack_di_symbolic(n_row, n_col, Ap, Ai, Ax, Symbolic, Control, Info)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: n_row
integer, intent(in) :: n_col
integer, intent(in), target :: Ap(*)
integer, intent(in), target :: Ai(*)
real(kind=r8), intent(in), optional target :: Ax(*)
type(c_ptr), optional :: Symbolic
real(kind=r8), optional target :: Control(0:UMFPACK_CONTROL-1)
real(kind=r8), optional target :: Info(0:UMFPACK_INFO-1)
Return Value integer
Calls
Called by
Contents
None
Call graph
umfpack_di_symbolic calls c_umfpack_di_symbolic
umfpack_symbolic calls umfpack_di_symbolic
s_umfpack_di_symbolic calls umfpack_di_symbolic
s_umfpack_symbolic calls s_umfpack_di_symbolic
umfpack_di_operator_csc calls s_umfpack_di_symbolic
umfpack_di_operator_csr calls s_umfpack_di_symbolic
umfpack_di_operator_pcsr calls s_umfpack_di_symbolic
analyse_solver calls s_umfpack_di_symbolic
umfpack_di_operator_pcsc calls s_umfpack_di_symbolic
umf4zsym calls s_umfpack_symbolic, umf4csym_ip, umf4zsym_ip, umf4zsym
operator(.umfpack.) calls umfpack_di_operator_csc, umfpack_di_operator_csr, umfpack_di_operator_pcsr, umfpack_di_operator_pcsc
umf4csym_ip calls s_umfpack_symbolic
solve_syst calls analyse_solver
umf4csym calls s_umfpack_symbolic, umf4csym_ip, umf4csym
umf4zsym_ip calls s_umfpack_symbolic
umf4sym_ip calls s_umfpack_symbolic
umf4sym calls s_umfpack_symbolic, umf4csym_ip, umf4zsym_ip, umf4sym_ip, umf4sym
test_solvers calls solve_syst