umfpack_ci_symbolic – MSOLV-fortran
umfpack_ci_symbolic Function
36 statements
Source File
public function umfpack_ci_symbolic(n_row, n_col, Ap, Ai, Ax, Symbolic, Control, Info)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: n_row
integer, intent(in) :: n_col
integer, intent(in), target :: Ap(*)
integer, intent(in), target :: Ai(*)
complex(kind=r8), intent(in), target :: Ax(*)
type(c_ptr), optional :: Symbolic
real(kind=r8), optional target :: Control(0:UMFPACK_CONTROL-1)
real(kind=r8), optional target :: Info(0:UMFPACK_INFO-1)
Return Value integer
Calls
Called by
Contents
None
Call graph
umfpack_ci_symbolic calls c_umfpack_zi_symbolic
umfpack_zi_symbolic calls umfpack_ci_symbolic, umfpack_zi_symbolic
umfpack_symbolic calls umfpack_ci_symbolic
s_umfpack_ci_symbolic calls umfpack_ci_symbolic
s_umfpack_symbolic calls s_umfpack_ci_symbolic
umfpack_ci_operator_pcsr calls s_umfpack_ci_symbolic
s_umfpack_zi_symbolic calls s_umfpack_ci_symbolic, s_umfpack_zi_symbolic
umfpack_ci_operator_csc calls s_umfpack_ci_symbolic
umfpack_ci_operator_pcsc calls s_umfpack_ci_symbolic
umfpack_ci_operator_csr calls s_umfpack_ci_symbolic
operator(.umfpack.) calls umfpack_ci_operator_pcsr, umfpack_ci_operator_csc, umfpack_ci_operator_pcsc, umfpack_ci_operator_csr
umf4zsym calls s_umfpack_symbolic, umf4zsym_ip, umf4csym_ip, umf4zsym
umf4csym calls s_umfpack_symbolic, umf4csym_ip, umf4csym
umf4sym_ip calls s_umfpack_symbolic
umf4zsym_ip calls s_umfpack_symbolic
umf4csym_ip calls s_umfpack_symbolic
umf4sym calls s_umfpack_symbolic, umf4sym_ip, umf4zsym_ip, umf4csym_ip, umf4sym