c_umfpack_zi_free_symbolic – MSOLV-fortran
c_umfpack_zi_free_symbolic Interface
172 statements
Source File
interface
Called by
public subroutine c_umfpack_zi_free_symbolic(Symbolic) bind(c,name="0")
Arguments
Type Intent Optional Attributes Name
type(c_ptr) :: Symbolic
Call graph
umfpack_zi_free_symbolic calls c_umfpack_zi_free_symbolic
umfpack_zi_operator_pcsc calls umfpack_zi_free_symbolic
umfpack_ci_operator_pcsc calls umfpack_zi_free_symbolic
umfpack_zi_operator_csr calls umfpack_zi_free_symbolic
umfpack_ci_operator_csr calls umfpack_zi_free_symbolic
umfpack_free_symbolic calls umfpack_zi_free_symbolic
umfpack_ci_operator_pcsr calls umfpack_zi_free_symbolic
s_umfpack_zi_free_symbolic calls umfpack_zi_free_symbolic
umfpack_ci_operator_csc calls umfpack_zi_free_symbolic
umfpack_zi_operator_pcsr calls umfpack_zi_free_symbolic
umfpack_zi_operator_csc calls umfpack_zi_free_symbolic
umf4cfsym_ip calls umfpack_free_symbolic
umf4fsym_ip calls umfpack_free_symbolic
umf4fsym calls umfpack_free_symbolic, umf4fsym_ip, umf4fsym
umf4cfsym calls umfpack_free_symbolic, umf4cfsym_ip, umf4cfsym
s_umfpack_free_symbolic calls umfpack_free_symbolic
umf4zfsym calls umfpack_free_symbolic, umf4zfsym_ip, umf4zfsym
operator(.umfpack.) calls umfpack_zi_operator_pcsc, umfpack_ci_operator_pcsc, umfpack_zi_operator_csr, umfpack_ci_operator_csr, umfpack_ci_operator_pcsr, umfpack_ci_operator_csc, umfpack_zi_operator_pcsr, umfpack_zi_operator_csc
umf4zfsym_ip calls umfpack_free_symbolic