c_umfpack_di_report_info – MSOLV-fortran
c_umfpack_di_report_info Interface
172 statements
Source File
interface
Called by
public subroutine c_umfpack_di_report_info(Control, Info) bind(c,name="0")
Arguments
Type Intent Optional Attributes Name
type(c_ptr), value :: Control
type(c_ptr), value :: Info
Call graph
umfpack_di_report_info calls c_umfpack_di_report_info
umfpack_report_info calls umfpack_di_report_info
s_umfpack_di_report_info calls umfpack_di_report_info
close_solver calls umfpack_di_report_info
umf4cpinf calls umfpack_report_info
solve_syst calls close_solver
umf4pinf calls umfpack_report_info
umf4zpinf calls umfpack_report_info
s_umfpack_report_info calls umfpack_report_info
test_solvers calls solve_syst