c_umfpack_zi_free_numeric – MSOLV-fortran
c_umfpack_zi_free_numeric Interface
172 statements
Source File
interface
Called by
public subroutine c_umfpack_zi_free_numeric(Numeric) bind(c,name="0")
Arguments
Type Intent Optional Attributes Name
type(c_ptr) :: Numeric
Call graph
umfpack_zi_free_numeric calls c_umfpack_zi_free_numeric
umfpack_zi_operator_csc calls umfpack_zi_free_numeric
umfpack_free_numeric calls umfpack_zi_free_numeric
umfpack_ci_operator_pcsc calls umfpack_zi_free_numeric
umfpack_zi_operator_pcsc calls umfpack_zi_free_numeric
s_umfpack_zi_free_numeric calls umfpack_zi_free_numeric
umfpack_ci_operator_csr calls umfpack_zi_free_numeric
umfpack_ci_operator_csc calls umfpack_zi_free_numeric
umfpack_zi_operator_pcsr calls umfpack_zi_free_numeric
umfpack_ci_operator_pcsr calls umfpack_zi_free_numeric
umfpack_zi_operator_csr calls umfpack_zi_free_numeric
umf4zfnum calls umfpack_free_numeric, umf4zfnum_ip, umf4zfnum
s_umfpack_free_numeric calls umfpack_free_numeric
umf4fnum_ip calls umfpack_free_numeric
umf4zfnum_ip calls umfpack_free_numeric
umf4cfnum_ip calls umfpack_free_numeric
operator(.umfpack.) calls umfpack_zi_operator_csc, umfpack_ci_operator_pcsc, umfpack_zi_operator_pcsc, umfpack_ci_operator_csr, umfpack_ci_operator_csc, umfpack_zi_operator_pcsr, umfpack_ci_operator_pcsr, umfpack_zi_operator_csr
umf4fnum calls umfpack_free_numeric, umf4fnum_ip, umf4fnum
umf4cfnum calls umfpack_free_numeric, umf4cfnum_ip, umf4cfnum