c_umfpack_zi_save_numeric – MSOLV-fortran
c_umfpack_zi_save_numeric Interface
172 statements
Source File
interface
Called by
public function c_umfpack_zi_save_numeric(Numeric, filename) bind(c,name='umfpack_zi_save_numeric')
Arguments
Type Intent Optional Attributes Name
type(c_ptr), value :: Numeric
character(len=1,c_char) :: filename(*)
Return Value integer(kind=c_int)
Call graph
umfpack_zi_save_numeric calls c_umfpack_zi_save_numeric
s_umfpack_zi_save_numeric calls umfpack_zi_save_numeric
umfpack_save_numeric calls umfpack_zi_save_numeric
umf4snum_ip calls umfpack_save_numeric
umf4csnum_ip calls umfpack_save_numeric
umf4zsnum_ip calls umfpack_save_numeric
umf4snum calls umfpack_save_numeric, umf4snum_ip, umf4snum
s_umfpack_save_numeric calls umfpack_save_numeric
umf4zsnum calls umfpack_save_numeric, umf4zsnum_ip, umf4zsnum
umf4csnum calls umfpack_save_numeric, umf4csnum_ip, umf4csnum