c_umfpack_zi_defaults – MSOLV-fortran
c_umfpack_zi_defaults Interface
172 statements
Source File
interface
Called by
public subroutine c_umfpack_zi_defaults(Control) bind(c,name="0")
Arguments
Type Intent Optional Attributes Name
type(c_ptr), value :: Control
Call graph
umfpack_zi_defaults calls c_umfpack_zi_defaults
umfpack_defaults calls umfpack_zi_defaults
s_umfpack_zi_defaults calls umfpack_zi_defaults
s_umfpack_defaults calls umfpack_defaults
umf4zdef calls umfpack_defaults
umf4def calls umfpack_defaults
umf4cdef calls umfpack_defaults