c_umfpack_zi_load_numeric – MSOLV-fortran
c_umfpack_zi_load_numeric Interface
172 statements
Source File
interface
Called by
public function c_umfpack_zi_load_numeric(Numeric, filename) bind(c,name='umfpack_zi_load_numeric')
Arguments
Type Intent Optional Attributes Name
type(c_ptr) :: Numeric
character(len=1,c_char) :: filename(*)
Return Value integer(kind=c_int)
Call graph
umfpack_zi_load_numeric calls c_umfpack_zi_load_numeric
umfpack_load_numeric calls umfpack_zi_load_numeric
s_umfpack_zi_load_numeric calls umfpack_zi_load_numeric
umf4clnum_ip calls umfpack_load_numeric
umf4zlnum_ip calls umfpack_load_numeric
umf4zlnum calls umfpack_load_numeric, umf4zlnum_ip, umf4zlnum
umf4clnum calls umfpack_load_numeric, umf4clnum_ip, umf4clnum
umf4lnum_ip calls umfpack_load_numeric
umf4lnum calls umfpack_load_numeric, umf4lnum_ip, umf4lnum
s_umfpack_load_numeric calls umfpack_load_numeric