c_umfpack_zi_load_symbolic – MSOLV-fortran
c_umfpack_zi_load_symbolic Interface
172 statements
Source File
interface
Called by
public function c_umfpack_zi_load_symbolic(Symbolic, filename) bind(c,name='umfpack_zi_load_symbolic')
Arguments
Type Intent Optional Attributes Name
type(c_ptr) :: Symbolic
character(len=1,c_char) :: filename(*)
Return Value integer(kind=c_int)
Call graph
umfpack_zi_load_symbolic calls c_umfpack_zi_load_symbolic
umfpack_load_symbolic calls umfpack_zi_load_symbolic
s_umfpack_zi_load_symbolic calls umfpack_zi_load_symbolic
umf4zlsym_ip calls umfpack_load_symbolic
umf4lsym calls umfpack_load_symbolic, umf4lsym_ip, umf4lsym
umf4lsym_ip calls umfpack_load_symbolic
umf4clsym_ip calls umfpack_load_symbolic
umf4zlsym calls umfpack_load_symbolic, umf4zlsym_ip, umf4zlsym
s_umfpack_load_symbolic calls umfpack_load_symbolic
umf4clsym calls umfpack_load_symbolic, umf4clsym_ip, umf4clsym