c_umfpack_zi_save_symbolic – MSOLV-fortran
c_umfpack_zi_save_symbolic Interface
172 statements
Source File
interface
Called by
public function c_umfpack_zi_save_symbolic(Symbolic, filename) bind(c,name='umfpack_zi_save_symbolic')
Arguments
Type Intent Optional Attributes Name
type(c_ptr), value :: Symbolic
character(len=1,c_char) :: filename(*)
Return Value integer(kind=c_int)
Call graph
umfpack_zi_save_symbolic calls c_umfpack_zi_save_symbolic
s_umfpack_zi_save_symbolic calls umfpack_zi_save_symbolic
umfpack_save_symbolic calls umfpack_zi_save_symbolic
umf4cssym calls umfpack_save_symbolic, umf4cssym_ip, umf4cssym
umf4cssym_ip calls umfpack_save_symbolic
s_umfpack_save_symbolic calls umfpack_save_symbolic
umf4zssym calls umfpack_save_symbolic, umf4zssym_ip, umf4zssym
umf4zssym_ip calls umfpack_save_symbolic
umf4ssym calls umfpack_save_symbolic, umf4ssym_ip, umf4ssym
umf4ssym_ip calls umfpack_save_symbolic