dCreate_Dense_Matrix – MSOLV-fortran
dCreate_Dense_Matrix Interface
98 statements
Source File
interface
Called by
private subroutine dCreate_Dense_Matrix(BX, m, n, x, ldx, stype, dtype, mtype) bind(c, name="0")
Arguments
Type Intent Optional Attributes Name
type(SUPERMATRIX), intent(out) :: BX
integer(kind=C_INT), intent(in), value :: m
integer(kind=C_INT), intent(in), value :: n
real(kind=C_DOUBLE), intent(in) :: x(*)
integer(kind=C_INT), intent(in), value :: ldx
integer(kind=C_INT), intent(in), value :: stype
integer(kind=C_INT), intent(in), value :: dtype
integer(kind=C_INT), intent(in), value :: mtype
Call graph
prep_superlu calls dcreate_dense_matrix
solv_superlu calls prep_superlu
analyse_solver calls prep_superlu
solution_solver calls solv_superlu
solve_syst calls analyse_solver, solution_solver
test_solvers calls solve_syst