Destroy_SuperNode_Matrix – MSOLV-fortran
Destroy_SuperNode_Matrix Interface
98 statements
Source File
interface
Called by
public subroutine Destroy_SuperNode_Matrix(A) bind(c, name="0")
Arguments
Type Intent Optional Attributes Name
type(SUPERMATRIX), intent(in) :: A
Call graph
solv_superlu calls destroy_supernode_matrix
solution_solver calls solv_superlu
solve_syst calls solution_solver
test_solvers calls solve_syst