dgssvx – MSOLV-fortran
dgssvx Interface
98 statements
Source File
interface
Called by
private subroutine dgssvx(options, A, perm_c, perm_r, etree, equed, R, C, L, U, work, lwork, B, X, recip_pivot_growth, rcond, ferr, berr, Glu, mem_usage, stat, info) bind(c, name="0")
Arguments
Type Intent Optional Attributes Name
type(SUPERLU_OPTIONS_T), intent(in) :: options
type(SUPERMATRIX), intent(inout) :: A
integer(kind=C_INT), intent(inout) :: perm_c(*)
integer(kind=C_INT), intent(inout) :: perm_r(*)
integer(kind=C_INT), intent(inout) :: etree(*)
character(kind=C_CHAR), intent(inout) :: equed(*)
real(kind=C_DOUBLE), intent(inout) :: R(*)
real(kind=C_DOUBLE), intent(inout) :: C(*)
type(SUPERMATRIX), intent(inout) :: L
type(SUPERMATRIX), intent(inout) :: U
type(C_PTR), intent(out) :: work
integer(kind=C_INT), intent(in), value :: lwork
type(SUPERMATRIX), intent(inout) :: B
type(SUPERMATRIX), intent(out) :: X
real(kind=C_DOUBLE), intent(out) :: recip_pivot_growth(*)
real(kind=C_DOUBLE), intent(out) :: rcond(*)
real(kind=C_DOUBLE), intent(out) :: ferr(*)
real(kind=C_DOUBLE), intent(out) :: berr(*)
type(GLOBALLU_T), intent(inout) :: Glu
type(MEM_USAGE_T), intent(out) :: mem_usage
type(SUPERLUSTAT_T), intent(out) :: stat
integer(kind=C_INT), intent(out) :: info
Call graph
fact_superlu calls dgssvx
solv_superlu calls dgssvx
solution_solver calls solv_superlu
solve_syst calls solution_solver
test_solvers calls solve_syst