operator(.umfpack.) – MSOLV-fortran
operator(.umfpack.) Interface
3 statements
Source File
public interface operator(.umfpack.)
Calls
Contents
Module Procedures
umfpack_di_operator_CSC umfpack_zi_operator_CSC umfpack_ci_operator_CSC umfpack_di_operator_CSR umfpack_zi_operator_CSR umfpack_ci_operator_CSR umfpack_di_operator_pCSC umfpack_zi_operator_pCSC umfpack_ci_operator_pCSC umfpack_di_operator_pCSR umfpack_zi_operator_pCSR umfpack_ci_operator_pCSR
Module Procedures
public function umfpack_di_operator_CSC(A, B) result(X)
Arguments
Type Intent Optional Attributes Name
type(tCSC_di), intent(in) :: A
real(kind=c_double), intent(in) :: B(*)
Return Value real(kind=c_double) (size(A%Ap)-1)
public function umfpack_zi_operator_CSC(A, B) result(X)
Arguments
Type Intent Optional Attributes Name
type(tCSC_zi), intent(in) :: A
type(tVec_zi), intent(in) :: B
Return Value type(tVec_zi)
public function umfpack_ci_operator_CSC(A, B) result(X)
Arguments
Type Intent Optional Attributes Name
type(tCSC_ci), intent(in) :: A
complex(kind=c_double), intent(in) :: B(*)
Return Value complex(kind=c_double) (size(A%Ap)-1)
public function umfpack_di_operator_CSR(A, B) result(X)
Arguments
Type Intent Optional Attributes Name
type(tCSR_di), intent(in) :: A
real(kind=c_double), intent(in) :: B(*)
Return Value real(kind=c_double) (size(A%Ap)-1)
public function umfpack_zi_operator_CSR(A, B) result(X)
Arguments
Type Intent Optional Attributes Name
type(tCSR_zi), intent(in) :: A
type(tVec_zi), intent(in) :: B
Return Value type(tVec_zi)
public function umfpack_ci_operator_CSR(A, B) result(X)
Arguments
Type Intent Optional Attributes Name
type(tCSR_ci), intent(in) :: A
complex(kind=c_double), intent(in) :: B(*)
Return Value complex(kind=c_double) (size(A%Ap)-1)
public function umfpack_di_operator_pCSC(A, B) result(X)
Arguments
Type Intent Optional Attributes Name
type(pCSC_di), intent(in) :: A
real(kind=c_double), intent(in) :: B(:)
Return Value real(kind=c_double) (size(A%Ap)-1)
public function umfpack_zi_operator_pCSC(A, B) result(X)
Arguments
Type Intent Optional Attributes Name
type(pCSC_zi), intent(in) :: A
type(pVec_zi), intent(in) :: B
Return Value type(tVec_zi)
public function umfpack_ci_operator_pCSC(A, B) result(X)
Arguments
Type Intent Optional Attributes Name
type(pCSC_ci), intent(in) :: A
complex(kind=c_double), intent(in) :: B(*)
Return Value complex(kind=c_double) (size(A%Ap)-1)
public function umfpack_di_operator_pCSR(A, B) result(X)
Arguments
Type Intent Optional Attributes Name
type(pCSR_di), intent(in) :: A
real(kind=c_double), intent(in) :: B(:)
Return Value real(kind=c_double) (size(A%Ap)-1)
public function umfpack_zi_operator_pCSR(A, B) result(X)
Arguments
Type Intent Optional Attributes Name
type(pCSR_zi), intent(in) :: A
type(pVec_zi), intent(in) :: B
Return Value type(tVec_zi)
public function umfpack_ci_operator_pCSR(A, B) result(X)
Arguments
Type Intent Optional Attributes Name
type(pCSR_ci), intent(in) :: A
complex(kind=c_double), intent(in) :: B(*)
Return Value complex(kind=c_double) (size(A%Ap)-1)
Call graph
operator(.umfpack.) calls umfpack_di_operator_csc, umfpack_zi_operator_pcsc, umfpack_ci_operator_pcsr, umfpack_ci_operator_csr, umfpack_ci_operator_pcsc, umfpack_di_operator_csr, umfpack_di_operator_pcsr, umfpack_zi_operator_csc, umfpack_zi_operator_pcsr, umfpack_zi_operator_csr, umfpack_ci_operator_csc, umfpack_di_operator_pcsc
umfpack_di_operator_csc calls s_umfpack_di_numeric, umfpack_di_free_numeric, s_umfpack_di_symbolic, umfpack_di_free_symbolic, s_umfpack_di_solve
umfpack_zi_operator_pcsc calls umfpack_zi_free_symbolic, s_umfpack_zi_numeric, s_umfpack_zi_symbolic, umfpack_zi_free_numeric, s_umfpack_zi_solve
umfpack_ci_operator_pcsr calls s_umfpack_ci_numeric, s_umfpack_ci_symbolic, umfpack_zi_free_symbolic, s_umfpack_ci_solve, umfpack_zi_free_numeric
umfpack_ci_operator_csr calls s_umfpack_ci_numeric, s_umfpack_ci_symbolic, umfpack_zi_free_symbolic, s_umfpack_ci_solve, umfpack_zi_free_numeric
umfpack_ci_operator_pcsc calls s_umfpack_ci_numeric, s_umfpack_ci_symbolic, umfpack_zi_free_symbolic, s_umfpack_ci_solve, umfpack_zi_free_numeric
umfpack_di_operator_csr calls s_umfpack_di_numeric, umfpack_di_free_numeric, s_umfpack_di_symbolic, umfpack_di_free_symbolic, s_umfpack_di_solve
umfpack_di_operator_pcsr calls s_umfpack_di_numeric, umfpack_di_free_numeric, s_umfpack_di_symbolic, umfpack_di_free_symbolic, s_umfpack_di_solve
umfpack_zi_operator_csc calls umfpack_zi_free_symbolic, s_umfpack_zi_numeric, s_umfpack_zi_symbolic, umfpack_zi_free_numeric, s_umfpack_zi_solve
umfpack_zi_operator_pcsr calls umfpack_zi_free_symbolic, s_umfpack_zi_numeric, s_umfpack_zi_symbolic, umfpack_zi_free_numeric, s_umfpack_zi_solve
umfpack_zi_operator_csr calls umfpack_zi_free_symbolic, s_umfpack_zi_numeric, s_umfpack_zi_symbolic, umfpack_zi_free_numeric, s_umfpack_zi_solve
umfpack_ci_operator_csc calls s_umfpack_ci_numeric, s_umfpack_ci_symbolic, umfpack_zi_free_symbolic, s_umfpack_ci_solve, umfpack_zi_free_numeric
umfpack_di_operator_pcsc calls s_umfpack_di_numeric, umfpack_di_free_numeric, s_umfpack_di_symbolic, umfpack_di_free_symbolic, s_umfpack_di_solve
s_umfpack_di_numeric calls umfpack_di_numeric
s_umfpack_ci_numeric calls umfpack_ci_numeric
s_umfpack_ci_symbolic calls umfpack_ci_symbolic
umfpack_di_free_numeric calls c_umfpack_di_free_numeric
s_umfpack_di_symbolic calls umfpack_di_symbolic
umfpack_zi_free_symbolic calls c_umfpack_zi_free_symbolic
s_umfpack_zi_numeric calls s_umfpack_ci_numeric, s_umfpack_zi_numeric
s_umfpack_ci_solve calls umfpack_ci_solve
s_umfpack_zi_symbolic calls s_umfpack_ci_symbolic, s_umfpack_zi_symbolic
umfpack_zi_free_numeric calls c_umfpack_zi_free_numeric
umfpack_di_free_symbolic calls c_umfpack_di_free_symbolic
s_umfpack_di_solve calls umfpack_di_solve
s_umfpack_zi_solve calls s_umfpack_ci_solve, s_umfpack_zi_solve
umfpack_di_solve calls c_umfpack_di_solve
umfpack_ci_solve calls c_umfpack_zi_solve
umfpack_di_symbolic calls c_umfpack_di_symbolic
umfpack_di_numeric calls c_umfpack_di_numeric
umfpack_ci_symbolic calls c_umfpack_zi_symbolic
umfpack_ci_numeric calls c_umfpack_zi_numeric