s_umfpack_symbolic – MSOLV-fortran
s_umfpack_symbolic Interface
3 statements
Source File
public interface s_umfpack_symbolic
Calls
Called by
Contents
Module Procedures
s_umfpack_di_symbolic s_umfpack_zi_symbolic s_umfpack_ci_symbolic
Module Procedures
public subroutine s_umfpack_di_symbolic(n_row, n_col, Ap, Ai, Ax, Symbolic, Control, Info, status)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: n_row
integer, intent(in) :: n_col
integer, intent(in) :: Ap(*)
integer, intent(in) :: Ai(*)
real(kind=r8), intent(in), optional :: Ax(*)
type(c_ptr), optional :: Symbolic
real(kind=r8), optional :: Control(0:UMFPACK_CONTROL-1)
real(kind=r8), optional :: Info(0:UMFPACK_INFO-1)
integer, optional :: status
public interface s_umfpack_zi_symbolic()
Arguments
None
public subroutine s_umfpack_ci_symbolic(n_row, n_col, Ap, Ai, Ax, Symbolic, Control, Info, status)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: n_row
integer, intent(in) :: n_col
integer, intent(in) :: Ap(*)
integer, intent(in) :: Ai(*)
complex(kind=r8), intent(in) :: Ax(*)
type(c_ptr), optional :: Symbolic
real(kind=r8), optional :: Control(0:UMFPACK_CONTROL-1)
real(kind=r8), optional :: Info(0:UMFPACK_INFO-1)
integer, optional :: status
Call graph
s_umfpack_symbolic calls s_umfpack_di_symbolic, s_umfpack_ci_symbolic, s_umfpack_zi_symbolic
s_umfpack_di_symbolic calls umfpack_di_symbolic
s_umfpack_ci_symbolic calls umfpack_ci_symbolic
s_umfpack_zi_symbolic calls s_umfpack_ci_symbolic, s_umfpack_zi_symbolic
umfpack_di_symbolic calls c_umfpack_di_symbolic
umfpack_ci_symbolic calls c_umfpack_zi_symbolic
umf4zsym calls s_umfpack_symbolic, umf4zsym_ip, umf4csym_ip, umf4zsym
umf4sym calls s_umfpack_symbolic, umf4sym_ip, umf4zsym_ip, umf4csym_ip, umf4sym
umf4sym_ip calls s_umfpack_symbolic
umf4zsym_ip calls s_umfpack_symbolic
umf4csym_ip calls s_umfpack_symbolic
umf4csym calls s_umfpack_symbolic, umf4csym_ip, umf4csym