s_umfpack_numeric – MSOLV-fortran
s_umfpack_numeric Interface
3 statements
Source File
public interface s_umfpack_numeric
Calls
Called by
Contents
Module Procedures
s_umfpack_di_numeric s_umfpack_zi_numeric s_umfpack_ci_numeric
Module Procedures
public subroutine s_umfpack_di_numeric(Ap, Ai, Ax, Symbolic, Numeric, Control, Info, status)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: Ap(*)
integer, intent(in) :: Ai(*)
real(kind=r8), intent(in) :: Ax(*)
type(c_ptr), intent(in), optional :: Symbolic
type(c_ptr), optional :: Numeric
real(kind=r8), optional :: Control(0:UMFPACK_CONTROL-1)
real(kind=r8), optional :: Info(0:UMFPACK_INFO-1)
integer, optional :: status
public interface s_umfpack_zi_numeric()
Arguments
None
public subroutine s_umfpack_ci_numeric(Ap, Ai, Ax, Symbolic, Numeric, Control, Info, status)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: Ap(*)
integer, intent(in) :: Ai(*)
complex(kind=r8), intent(in) :: Ax(*)
type(c_ptr), intent(in), optional :: Symbolic
type(c_ptr), optional :: Numeric
real(kind=r8), optional :: Control(0:UMFPACK_CONTROL-1)
real(kind=r8), optional :: Info(0:UMFPACK_INFO-1)
integer, optional :: status
Call graph
s_umfpack_numeric calls s_umfpack_di_numeric, s_umfpack_ci_numeric, s_umfpack_zi_numeric
s_umfpack_di_numeric calls umfpack_di_numeric
s_umfpack_ci_numeric calls umfpack_ci_numeric
s_umfpack_zi_numeric calls s_umfpack_ci_numeric, s_umfpack_zi_numeric
umfpack_di_numeric calls c_umfpack_di_numeric
umfpack_ci_numeric calls c_umfpack_zi_numeric
umf4num_ip calls s_umfpack_numeric
umf4znum calls s_umfpack_numeric, umf4znum_ip, umf4cnum_ip, umf4znum
umf4cnum calls s_umfpack_numeric, umf4cnum_ip, umf4cnum
umf4znum_ip calls s_umfpack_numeric
umf4cnum_ip calls s_umfpack_numeric
umf4num calls s_umfpack_numeric, umf4num_ip, umf4znum_ip, umf4cnum_ip, umf4num