s_umfpack_solve – MSOLV-fortran
s_umfpack_solve Interface
3 statements
Source File
public interface s_umfpack_solve
Calls
Called by
Contents
Module Procedures
s_umfpack_di_solve s_umfpack_zi_solve s_umfpack_ci_solve
Module Procedures
public subroutine s_umfpack_di_solve(sys, Ap, Ai, Ax, X, B, Numeric, Control, Info, status)
Arguments
Type Intent Optional Attributes Name
integer, intent(in), optional :: sys
integer, intent(in), optional :: Ap(*)
integer, intent(in), optional :: Ai(*)
real(kind=r8), intent(in), optional :: Ax(*)
real(kind=r8), intent(out) :: X(*)
real(kind=r8), intent(in) :: B(*)
type(c_ptr), intent(in), optional :: Numeric
real(kind=r8), optional :: Control(0:UMFPACK_CONTROL-1)
real(kind=r8), optional :: Info(0:UMFPACK_INFO-1)
integer, optional :: status
public interface s_umfpack_zi_solve()
Arguments
None
public subroutine s_umfpack_ci_solve(sys, Ap, Ai, Ax, Xx, Bx, Numeric, Control, Info, status)
Arguments
Type Intent Optional Attributes Name
integer, intent(in), optional :: sys
integer, intent(in), optional :: Ap(*)
integer, intent(in), optional :: Ai(*)
complex(kind=r8), intent(in), optional :: Ax(*)
complex(kind=r8), intent(out) :: Xx(*)
complex(kind=r8), intent(in) :: Bx(*)
type(c_ptr), intent(in), optional :: Numeric
real(kind=r8), optional :: Control(0:UMFPACK_CONTROL-1)
real(kind=r8), optional :: Info(0:UMFPACK_INFO-1)
integer, optional :: status
Call graph
s_umfpack_solve calls s_umfpack_di_solve, s_umfpack_zi_solve, s_umfpack_ci_solve
s_umfpack_di_solve calls umfpack_di_solve
s_umfpack_zi_solve calls s_umfpack_zi_solve, s_umfpack_ci_solve
s_umfpack_ci_solve calls umfpack_ci_solve
umfpack_ci_solve calls c_umfpack_zi_solve
umfpack_di_solve calls c_umfpack_di_solve
umf4solr_ip calls s_umfpack_solve
umf4zsolr calls s_umfpack_solve, umf4csolr_ip, umf4zsolr_ip, umf4zsolr
umf4sol calls s_umfpack_solve, umf4sol_ip, umf4sol
umf4zsol calls s_umfpack_solve
umf4csolr_ip calls s_umfpack_solve
umf4solr calls s_umfpack_solve, umf4solr_ip, umf4csolr_ip, umf4zsolr_ip, umf4solr
umf4csolr calls s_umfpack_solve, umf4csolr_ip, umf4csolr
umf4zsolr_ip calls s_umfpack_solve
umf4sol_ip calls s_umfpack_solve
umf4csol calls s_umfpack_solve