s_umfpack_free_numeric – MSOLV-fortran
s_umfpack_free_numeric Interface
3 statements
Source File
public interface s_umfpack_free_numeric
Calls
Contents
Module Procedures
umfpack_free_numeric
Module Procedures
public subroutine umfpack_free_numeric(Numeric, version)
Arguments
Type Intent Optional Attributes Name
type(c_ptr), optional :: Numeric
character(len=*), optional :: version
Call graph
s_umfpack_free_numeric calls umfpack_free_numeric
umfpack_free_numeric calls umfpack_zi_free_numeric, umfpack_di_free_numeric
umfpack_zi_free_numeric calls c_umfpack_zi_free_numeric
umfpack_di_free_numeric calls c_umfpack_di_free_numeric