StatInit – MSOLV-fortran
StatInit Interface
98 statements
Source File
interface
Called by
private subroutine StatInit(stat) bind(c, name="0")
Arguments
Type Intent Optional Attributes Name
type(SUPERLUSTAT_T), intent(out) :: stat
Call graph
solv_superlu calls statinit
fact_superlu calls statinit
solution_solver calls solv_superlu
solve_syst calls solution_solver
test_solvers calls solve_syst