umf4cfnum – MSOLV-fortran
umf4cfnum Interface
3 statements
Source File
public interface umf4cfnum
Calls
Contents
Module Procedures
umf4cfnum umf4cfnum_ip
Module Procedures
public interface umf4cfnum()
Arguments
None
public subroutine umf4cfnum_ip(Numeric)
Arguments
Type Intent Optional Attributes Name
integer(kind=ip) :: Numeric
Call graph
umf4cfnum calls umf4cfnum, umf4cfnum_ip
umf4cfnum_ip calls umfpack_free_numeric
umfpack_free_numeric calls umfpack_di_free_numeric, umfpack_zi_free_numeric
umfpack_di_free_numeric calls c_umfpack_di_free_numeric
umfpack_zi_free_numeric calls c_umfpack_zi_free_numeric