umf4zfsym – MSOLV-fortran
umf4zfsym Interface
3 statements
Source File
public interface umf4zfsym
Calls
Contents
Module Procedures
umf4zfsym umf4zfsym_ip
Module Procedures
public interface umf4zfsym()
Arguments
None
public subroutine umf4zfsym_ip(Symbolic)
Arguments
Type Intent Optional Attributes Name
integer(kind=ip) :: Symbolic
Call graph
umf4zfsym calls umf4zfsym, umf4zfsym_ip
umf4zfsym_ip calls umfpack_free_symbolic
umfpack_free_symbolic calls umfpack_zi_free_symbolic, umfpack_di_free_symbolic
umfpack_zi_free_symbolic calls c_umfpack_zi_free_symbolic
umfpack_di_free_symbolic calls c_umfpack_di_free_symbolic