umf4zlsym – MSOLV-fortran
umf4zlsym Interface
3 statements
Source File
public interface umf4zlsym
Calls
Contents
Module Procedures
umf4zlsym umf4zlsym_ip
Module Procedures
public interface umf4zlsym()
Arguments
None
public subroutine umf4zlsym_ip(Symbolic, filenum, status)
Arguments
Type Intent Optional Attributes Name
integer(kind=ip) :: Symbolic
integer, intent(in) :: filenum
integer, intent(out) :: status
Call graph
umf4zlsym calls umf4zlsym, umf4zlsym_ip
umf4zlsym_ip calls umfpack_load_symbolic
umfpack_load_symbolic calls umfpack_zi_load_symbolic, umfpack_di_load_symbolic
umfpack_zi_load_symbolic calls c_umfpack_zi_load_symbolic
umfpack_di_load_symbolic calls c_umfpack_di_load_symbolic