umf4zlnum – MSOLV-fortran
umf4zlnum Interface
3 statements
Source File
public interface umf4zlnum
Calls
Contents
Module Procedures
umf4zlnum umf4zlnum_ip
Module Procedures
public interface umf4zlnum()
Arguments
None
public subroutine umf4zlnum_ip(Numeric, filenum, status)
Arguments
Type Intent Optional Attributes Name
integer(kind=ip) :: Numeric
integer, intent(in) :: filenum
integer, intent(out) :: status
Call graph
umf4zlnum calls umf4zlnum, umf4zlnum_ip
umf4zlnum_ip calls umfpack_load_numeric
umfpack_load_numeric calls umfpack_zi_load_numeric, umfpack_di_load_numeric
umfpack_zi_load_numeric calls c_umfpack_zi_load_numeric
umfpack_di_load_numeric calls c_umfpack_di_load_numeric