umf4zssym – MSOLV-fortran
umf4zssym Interface
3 statements
Source File
public interface umf4zssym
Calls
Contents
Module Procedures
umf4zssym umf4zssym_ip
Module Procedures
public interface umf4zssym()
Arguments
None
public subroutine umf4zssym_ip(Symbolic, filenum, status)
Arguments
Type Intent Optional Attributes Name
integer(kind=ip) :: Symbolic
integer, intent(in) :: filenum
integer, intent(out) :: status
Call graph
umf4zssym calls umf4zssym, umf4zssym_ip
umf4zssym_ip calls umfpack_save_symbolic
umfpack_save_symbolic calls umfpack_di_save_symbolic, umfpack_zi_save_symbolic
umfpack_di_save_symbolic calls c_umfpack_di_save_symbolic
umfpack_zi_save_symbolic calls c_umfpack_zi_save_symbolic