umf4sol – MSOLV-fortran
umf4sol Interface
3 statements
Source File
public interface umf4sol
Calls
Contents
Module Procedures
umf4sol umf4sol_ip umf4zsol umf4zsol_ip umf4csol umf4csol_ip
Module Procedures
public interface umf4sol()
Arguments
None
public subroutine umf4sol_ip(sys, x, b, Numeric, Control, Info)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: sys
real(kind=r8), intent(out) :: x(*)
real(kind=r8), intent(in) :: b(*)
integer(kind=ip) :: Numeric
real(kind=r8) :: Control(0:UMFPACK_CONTROL-1)
real(kind=r8) :: Info(0:UMFPACK_INFO-1)
public interface umf4zsol()
Arguments
None
public subroutine umf4zsol_ip(sys, x, xz, b, bz, Numeric, Control, Info)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: sys
real(kind=r8), intent(out) :: x(*)
real(kind=r8), intent(out) :: xz(*)
real(kind=r8), intent(in) :: b(*)
real(kind=r8), intent(in) :: bz(*)
integer(kind=ip) :: Numeric
real(kind=r8) :: Control(0:UMFPACK_CONTROL-1)
real(kind=r8) :: Info(0:UMFPACK_INFO-1)
public interface umf4csol()
Arguments
None
public subroutine umf4csol_ip(sys, x, b, Numeric, Control, Info)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: sys
complex(kind=r8), intent(out) :: x(*)
complex(kind=r8), intent(in) :: b(*)
integer(kind=ip) :: Numeric
real(kind=r8) :: Control(0:UMFPACK_CONTROL-1)
real(kind=r8) :: Info(0:UMFPACK_INFO-1)
Call graph
umf4sol calls umf4sol, umf4csol, umf4zsol, umf4zsol_ip, umf4sol_ip, umf4csol_ip
umf4csol calls umf4csol, umf4csol_ip
umf4zsol calls umf4csol, umf4zsol, umf4zsol_ip, umf4csol_ip
umf4zsol_ip calls s_umfpack_zi_solve
umf4sol_ip calls s_umfpack_solve
umf4csol_ip calls s_umfpack_ci_solve
s_umfpack_zi_solve calls s_umfpack_zi_solve, s_umfpack_ci_solve
s_umfpack_solve calls s_umfpack_zi_solve, s_umfpack_ci_solve, s_umfpack_di_solve
s_umfpack_ci_solve calls umfpack_ci_solve
s_umfpack_di_solve calls umfpack_di_solve
umfpack_ci_solve calls c_umfpack_zi_solve
umfpack_di_solve calls c_umfpack_di_solve