umf4scal – MSOLV-fortran
umf4scal Interface
3 statements
Source File
public interface umf4scal
Calls
Contents
Module Procedures
umf4scal umf4scal_ip umf4zscal umf4zscal_ip umf4cscal umf4cscal_ip
Module Procedures
public interface umf4scal()
Arguments
None
public subroutine umf4scal_ip(x, b, Numeric, status)
Arguments
Type Intent Optional Attributes Name
real(kind=r8), intent(out) :: x(*)
real(kind=r8), intent(in) :: b(*)
integer(kind=ip) :: Numeric
integer, intent(out) :: status
public interface umf4zscal()
Arguments
None
public subroutine umf4zscal_ip(x, xz, b, bz, Numeric, status)
Arguments
Type Intent Optional Attributes Name
real(kind=r8), intent(out) :: x(*)
real(kind=r8), intent(out) :: xz(*)
real(kind=r8), intent(in) :: b(*)
real(kind=r8), intent(in) :: bz(*)
integer(kind=ip) :: Numeric
integer, intent(out) :: status
public interface umf4cscal()
Arguments
None
public subroutine umf4cscal_ip(x, b, Numeric, status)
Arguments
Type Intent Optional Attributes Name
complex(kind=r8), intent(out) :: x(*)
complex(kind=r8), intent(in) :: b(*)
integer(kind=ip) :: Numeric
integer, intent(out) :: status
Call graph
umf4scal calls umf4scal, umf4cscal, umf4scal_ip, umf4cscal_ip, umf4zscal, umf4zscal_ip
umf4cscal calls umf4cscal, umf4cscal_ip
umf4scal_ip calls umfpack_scale_function
umf4cscal_ip calls umfpack_scale_function
umf4zscal calls umf4cscal, umf4cscal_ip, umf4zscal, umf4zscal_ip
umf4zscal_ip calls umfpack_scale_function
umfpack_scale_function calls umfpack_di_scale, umfpack_ci_scale, umfpack_zi_scale
umfpack_di_scale calls c_umfpack_di_scale
umfpack_ci_scale calls c_umfpack_zi_scale
umfpack_zi_scale calls umfpack_ci_scale, umfpack_zi_scale