umf4num – MSOLV-fortran
umf4num Interface
3 statements
Source File
public interface umf4num
Calls
Contents
Module Procedures
umf4num umf4num_ip umf4znum umf4znum_ip umf4cnum umf4cnum_ip
Module Procedures
public interface umf4num()
Arguments
None
public subroutine umf4num_ip(Ap, Ai, Ax, Symbolic, Numeric, Control, Info)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: Ap(*)
integer, intent(in) :: Ai(*)
real(kind=r8), intent(in) :: Ax(*)
integer(kind=ip) :: Symbolic
integer(kind=ip) :: Numeric
real(kind=r8) :: Control(0:UMFPACK_CONTROL-1)
real(kind=r8) :: Info(0:UMFPACK_INFO-1)
public interface umf4znum()
Arguments
None
public subroutine umf4znum_ip(Ap, Ai, Ax, Az, Symbolic, Numeric, Control, Info)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: Ap(*)
integer, intent(in) :: Ai(*)
real(kind=r8), intent(in) :: Ax(*)
real(kind=r8), intent(in) :: Az(*)
integer(kind=ip) :: Symbolic
integer(kind=ip) :: Numeric
real(kind=r8) :: Control(0:UMFPACK_CONTROL-1)
real(kind=r8) :: Info(0:UMFPACK_INFO-1)
public interface umf4cnum()
Arguments
None
public subroutine umf4cnum_ip(Ap, Ai, Ax, Symbolic, Numeric, Control, Info)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: Ap(*)
integer, intent(in) :: Ai(*)
complex(kind=r8), intent(in) :: Ax(*)
integer(kind=ip) :: Symbolic
integer(kind=ip) :: Numeric
real(kind=r8) :: Control(0:UMFPACK_CONTROL-1)
real(kind=r8) :: Info(0:UMFPACK_INFO-1)
Call graph
umf4num calls umf4num, umf4num_ip, umf4cnum, umf4znum, umf4znum_ip, umf4cnum_ip
umf4num_ip calls s_umfpack_numeric
umf4cnum calls umf4cnum, umf4cnum_ip
umf4znum calls umf4cnum, umf4znum, umf4znum_ip, umf4cnum_ip
umf4znum_ip calls s_umfpack_numeric
umf4cnum_ip calls s_umfpack_numeric
s_umfpack_numeric calls s_umfpack_di_numeric, s_umfpack_zi_numeric, s_umfpack_ci_numeric
s_umfpack_di_numeric calls umfpack_di_numeric
s_umfpack_zi_numeric calls s_umfpack_zi_numeric, s_umfpack_ci_numeric
s_umfpack_ci_numeric calls umfpack_ci_numeric
umfpack_di_numeric calls c_umfpack_di_numeric
umfpack_ci_numeric calls c_umfpack_zi_numeric