umf4clnum – MSOLV-fortran
umf4clnum Interface
3 statements
Source File
public interface umf4clnum
Calls
Contents
Module Procedures
umf4clnum umf4clnum_ip
Module Procedures
public interface umf4clnum()
Arguments
None
public subroutine umf4clnum_ip(Numeric, filenum, status)
Arguments
Type Intent Optional Attributes Name
integer(kind=ip) :: Numeric
integer, intent(in) :: filenum
integer, intent(out) :: status
Call graph
umf4clnum calls umf4clnum, umf4clnum_ip
umf4clnum_ip calls umfpack_load_numeric
umfpack_load_numeric calls umfpack_di_load_numeric, umfpack_zi_load_numeric
umfpack_di_load_numeric calls c_umfpack_di_load_numeric
umfpack_zi_load_numeric calls c_umfpack_zi_load_numeric