umf4clsym – MSOLV-fortran
umf4clsym Interface
3 statements
Source File
public interface umf4clsym
Calls
Contents
Module Procedures
umf4clsym umf4clsym_ip
Module Procedures
public interface umf4clsym()
Arguments
None
public subroutine umf4clsym_ip(Symbolic, filenum, status)
Arguments
Type Intent Optional Attributes Name
integer(kind=ip) :: Symbolic
integer, intent(in) :: filenum
integer, intent(out) :: status
Call graph
umf4clsym calls umf4clsym, umf4clsym_ip
umf4clsym_ip calls umfpack_load_symbolic
umfpack_load_symbolic calls umfpack_zi_load_symbolic, umfpack_di_load_symbolic
umfpack_zi_load_symbolic calls c_umfpack_zi_load_symbolic
umfpack_di_load_symbolic calls c_umfpack_di_load_symbolic