umf4ssym – MSOLV-fortran
umf4ssym Interface
3 statements
Source File
public interface umf4ssym
Calls
Contents
Module Procedures
umf4ssym umf4ssym_ip
Module Procedures
public interface umf4ssym()
Arguments
None
public subroutine umf4ssym_ip(Symbolic, filenum, status)
Arguments
Type Intent Optional Attributes Name
integer(kind=ip) :: Symbolic
integer, intent(in) :: filenum
integer, intent(out) :: status
Call graph
umf4ssym calls umf4ssym, umf4ssym_ip
umf4ssym_ip calls umfpack_save_symbolic
umfpack_save_symbolic calls umfpack_zi_save_symbolic, umfpack_di_save_symbolic
umfpack_zi_save_symbolic calls c_umfpack_zi_save_symbolic
umfpack_di_save_symbolic calls c_umfpack_di_save_symbolic