umf4solr – MSOLV-fortran
umf4solr Interface
3 statements
Source File
public interface umf4solr
Calls
Contents
Module Procedures
umf4solr umf4solr_ip umf4zsolr umf4zsolr_ip umf4csolr umf4csolr_ip
Module Procedures
public interface umf4solr()
Arguments
None
public subroutine umf4solr_ip(sys, Ap, Ai, Ax, x, b, Numeric, Control, Info)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: sys
integer, intent(in) :: Ap(*)
integer, intent(in) :: Ai(*)
real(kind=r8), intent(in) :: Ax(*)
real(kind=r8), intent(out) :: x(*)
real(kind=r8), intent(in) :: b(*)
integer(kind=ip) :: Numeric
real(kind=r8) :: Control(0:UMFPACK_CONTROL-1)
real(kind=r8) :: Info(0:UMFPACK_INFO-1)
public interface umf4zsolr()
Arguments
None
public subroutine umf4zsolr_ip(sys, Ap, Ai, Ax, Az, x, xz, b, bz, Numeric, Control, Info)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: sys
integer, intent(in) :: Ap(*)
integer, intent(in) :: Ai(*)
real(kind=r8), intent(in) :: Ax(*)
real(kind=r8), intent(in) :: Az(*)
real(kind=r8), intent(out) :: x(*)
real(kind=r8), intent(out) :: xz(*)
real(kind=r8), intent(in) :: b(*)
real(kind=r8), intent(in) :: bz(*)
integer(kind=ip) :: Numeric
real(kind=r8) :: Control(0:UMFPACK_CONTROL-1)
real(kind=r8) :: Info(0:UMFPACK_INFO-1)
public interface umf4csolr()
Arguments
None
public subroutine umf4csolr_ip(sys, Ap, Ai, Ax, x, b, Numeric, Control, Info)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: sys
integer, intent(in) :: Ap(*)
integer, intent(in) :: Ai(*)
complex(kind=r8), intent(in) :: Ax(*)
complex(kind=r8), intent(out) :: x(*)
complex(kind=r8), intent(in) :: b(*)
integer(kind=ip) :: Numeric
real(kind=r8) :: Control(0:UMFPACK_CONTROL-1)
real(kind=r8) :: Info(0:UMFPACK_INFO-1)
Call graph
umf4solr calls umf4solr, umf4zsolr_ip, umf4zsolr, umf4csolr_ip, umf4solr_ip, umf4csolr
umf4zsolr_ip calls s_umfpack_solve
umf4zsolr calls umf4zsolr_ip, umf4zsolr, umf4csolr_ip, umf4csolr
umf4csolr_ip calls s_umfpack_solve
umf4solr_ip calls s_umfpack_solve
umf4csolr calls umf4csolr_ip, umf4csolr
s_umfpack_solve calls s_umfpack_zi_solve, s_umfpack_di_solve, s_umfpack_ci_solve
s_umfpack_zi_solve calls s_umfpack_zi_solve, s_umfpack_ci_solve
s_umfpack_di_solve calls umfpack_di_solve
s_umfpack_ci_solve calls umfpack_ci_solve
umfpack_ci_solve calls c_umfpack_zi_solve
umfpack_di_solve calls c_umfpack_di_solve