umf4snum – MSOLV-fortran
umf4snum Interface
3 statements
Source File
public interface umf4snum
Calls
Contents
Module Procedures
umf4snum umf4snum_ip
Module Procedures
public interface umf4snum()
Arguments
None
public subroutine umf4snum_ip(Numeric, filenum, status)
Arguments
Type Intent Optional Attributes Name
integer(kind=ip) :: Numeric
integer, intent(in) :: filenum
integer, intent(out) :: status
Call graph
umf4snum calls umf4snum, umf4snum_ip
umf4snum_ip calls umfpack_save_numeric
umfpack_save_numeric calls umfpack_zi_save_numeric, umfpack_di_save_numeric
umfpack_zi_save_numeric calls c_umfpack_zi_save_numeric
umfpack_di_save_numeric calls c_umfpack_di_save_numeric