umf4zfnum – MSOLV-fortran
umf4zfnum Interface
3 statements
Source File
public interface umf4zfnum
Calls
Contents
Module Procedures
umf4zfnum umf4zfnum_ip
Module Procedures
public interface umf4zfnum()
Arguments
None
public subroutine umf4zfnum_ip(Numeric)
Arguments
Type Intent Optional Attributes Name
integer(kind=ip) :: Numeric
Call graph
umf4zfnum calls umf4zfnum, umf4zfnum_ip
umf4zfnum_ip calls umfpack_free_numeric
umfpack_free_numeric calls umfpack_zi_free_numeric, umfpack_di_free_numeric
umfpack_zi_free_numeric calls c_umfpack_zi_free_numeric
umfpack_di_free_numeric calls c_umfpack_di_free_numeric