umf4cscal – MSOLV-fortran
umf4cscal Interface
3 statements
Source File
public interface umf4cscal
Calls
Called by
Contents
Module Procedures
umf4cscal umf4cscal_ip
Module Procedures
public interface umf4cscal()
Arguments
None
public subroutine umf4cscal_ip(x, b, Numeric, status)
Arguments
Type Intent Optional Attributes Name
complex(kind=r8), intent(out) :: x(*)
complex(kind=r8), intent(in) :: b(*)
integer(kind=ip) :: Numeric
integer, intent(out) :: status
Call graph
umf4cscal calls umf4cscal, umf4cscal_ip
umf4cscal_ip calls umfpack_scale_function
umfpack_scale_function calls umfpack_di_scale, umfpack_ci_scale, umfpack_zi_scale
umfpack_di_scale calls c_umfpack_di_scale
umfpack_ci_scale calls c_umfpack_zi_scale
umfpack_zi_scale calls umfpack_ci_scale, umfpack_zi_scale
umf4zscal calls umf4cscal, umf4zscal
umf4scal calls umf4cscal, umf4scal