umf4fnum – MSOLV-fortran
umf4fnum Interface
3 statements
Source File
public interface umf4fnum
Calls
Contents
Module Procedures
umf4fnum umf4fnum_ip
Module Procedures
public interface umf4fnum()
Arguments
None
public subroutine umf4fnum_ip(Numeric)
Arguments
Type Intent Optional Attributes Name
integer(kind=ip) :: Numeric
Call graph
umf4fnum calls umf4fnum, umf4fnum_ip
umf4fnum_ip calls umfpack_free_numeric
umfpack_free_numeric calls umfpack_zi_free_numeric, umfpack_di_free_numeric
umfpack_zi_free_numeric calls c_umfpack_zi_free_numeric
umfpack_di_free_numeric calls c_umfpack_di_free_numeric