umf4sym – MSOLV-fortran
umf4sym Interface
3 statements
Source File
public interface umf4sym
Calls
Contents
Module Procedures
umf4sym umf4sym_ip umf4zsym umf4zsym_ip umf4csym umf4csym_ip
Module Procedures
public interface umf4sym()
Arguments
None
public subroutine umf4sym_ip(m, n, Ap, Ai, Ax, Symbolic, Control, Info)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: m
integer, intent(in) :: n
integer, intent(in) :: Ap(*)
integer, intent(in) :: Ai(*)
real(kind=r8), intent(in) :: Ax(*)
integer(kind=ip) :: Symbolic
real(kind=r8) :: Control(0:UMFPACK_CONTROL-1)
real(kind=r8) :: Info(0:UMFPACK_INFO-1)
public interface umf4zsym()
Arguments
None
public subroutine umf4zsym_ip(m, n, Ap, Ai, Ax, Az, Symbolic, Control, Info)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: m
integer, intent(in) :: n
integer, intent(in) :: Ap(*)
integer, intent(in) :: Ai(*)
real(kind=r8), intent(in) :: Ax(*)
real(kind=r8), intent(in) :: Az(*)
integer(kind=ip) :: Symbolic
real(kind=r8) :: Control(0:UMFPACK_CONTROL-1)
real(kind=r8) :: Info(0:UMFPACK_INFO-1)
public interface umf4csym()
Arguments
None
public subroutine umf4csym_ip(m, n, Ap, Ai, Ax, Symbolic, Control, Info)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: m
integer, intent(in) :: n
integer, intent(in) :: Ap(*)
integer, intent(in) :: Ai(*)
complex(kind=r8), intent(in) :: Ax(*)
integer(kind=ip) :: Symbolic
real(kind=r8) :: Control(0:UMFPACK_CONTROL-1)
real(kind=r8) :: Info(0:UMFPACK_INFO-1)
Call graph
umf4sym calls umf4sym, umf4sym_ip, umf4zsym_ip, umf4csym, umf4csym_ip, umf4zsym
umf4sym_ip calls s_umfpack_symbolic
umf4zsym_ip calls s_umfpack_symbolic
umf4csym calls umf4csym, umf4csym_ip
umf4csym_ip calls s_umfpack_symbolic
umf4zsym calls umf4zsym_ip, umf4csym, umf4csym_ip, umf4zsym
s_umfpack_symbolic calls s_umfpack_di_symbolic, s_umfpack_ci_symbolic, s_umfpack_zi_symbolic
s_umfpack_di_symbolic calls umfpack_di_symbolic
s_umfpack_ci_symbolic calls umfpack_ci_symbolic
s_umfpack_zi_symbolic calls s_umfpack_ci_symbolic, s_umfpack_zi_symbolic
umfpack_di_symbolic calls c_umfpack_di_symbolic
umfpack_ci_symbolic calls c_umfpack_zi_symbolic