umf4fsym – MSOLV-fortran
umf4fsym Interface
3 statements
Source File
public interface umf4fsym
Calls
Contents
Module Procedures
umf4fsym umf4fsym_ip
Module Procedures
public interface umf4fsym()
Arguments
None
public subroutine umf4fsym_ip(Symbolic)
Arguments
Type Intent Optional Attributes Name
integer(kind=ip) :: Symbolic
Call graph
umf4fsym calls umf4fsym, umf4fsym_ip
umf4fsym_ip calls umfpack_free_symbolic
umfpack_free_symbolic calls umfpack_zi_free_symbolic, umfpack_di_free_symbolic
umfpack_zi_free_symbolic calls c_umfpack_zi_free_symbolic
umfpack_di_free_symbolic calls c_umfpack_di_free_symbolic