umf4csol – MSOLV-fortran
umf4csol Interface
3 statements
Source File
public interface umf4csol
Calls
Called by
Contents
Module Procedures
umf4csol umf4csol_ip
Module Procedures
public interface umf4csol()
Arguments
None
public subroutine umf4csol_ip(sys, x, b, Numeric, Control, Info)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: sys
complex(kind=r8), intent(out) :: x(*)
complex(kind=r8), intent(in) :: b(*)
integer(kind=ip) :: Numeric
real(kind=r8) :: Control(0:UMFPACK_CONTROL-1)
real(kind=r8) :: Info(0:UMFPACK_INFO-1)
Call graph
umf4csol calls umf4csol, umf4csol_ip
umf4csol_ip calls s_umfpack_ci_solve
s_umfpack_ci_solve calls umfpack_ci_solve
umfpack_ci_solve calls c_umfpack_zi_solve
umf4zsol calls umf4csol, umf4zsol
umf4sol calls umf4csol, umf4sol