umfpack_numeric – MSOLV-fortran
umfpack_numeric Interface
3 statements
Source File
public interface umfpack_numeric
Calls
Contents
Module Procedures
umfpack_di_numeric umfpack_zi_numeric umfpack_ci_numeric
Module Procedures
public function umfpack_di_numeric(Ap, Ai, Ax, Symbolic, Numeric, Control, Info)
Arguments
Type Intent Optional Attributes Name
integer, intent(in), target :: Ap(*)
integer, intent(in), target :: Ai(*)
real(kind=r8), intent(in), target :: Ax(*)
type(c_ptr), intent(in), optional :: Symbolic
type(c_ptr), optional :: Numeric
real(kind=r8), optional target :: Control(0:UMFPACK_CONTROL-1)
real(kind=r8), optional target :: Info(0:UMFPACK_INFO-1)
Return Value integer
public interface umfpack_zi_numeric()
Arguments
None
public function umfpack_ci_numeric(Ap, Ai, Ax, Symbolic, Numeric, Control, Info)
Arguments
Type Intent Optional Attributes Name
integer, intent(in), target :: Ap(*)
integer, intent(in), target :: Ai(*)
complex(kind=r8), intent(in), target :: Ax(*)
type(c_ptr), intent(in), optional :: Symbolic
type(c_ptr), optional :: Numeric
real(kind=r8), optional target :: Control(0:UMFPACK_CONTROL-1)
real(kind=r8), optional target :: Info(0:UMFPACK_INFO-1)
Return Value integer
Call graph
umfpack_numeric calls umfpack_zi_numeric, umfpack_di_numeric, umfpack_ci_numeric
umfpack_zi_numeric calls umfpack_zi_numeric, umfpack_ci_numeric
umfpack_di_numeric calls c_umfpack_di_numeric
umfpack_ci_numeric calls c_umfpack_zi_numeric