umfpack_symbolic – MSOLV-fortran
umfpack_symbolic Interface
3 statements
Source File
public interface umfpack_symbolic
Calls
Contents
Module Procedures
umfpack_di_symbolic umfpack_zi_symbolic umfpack_ci_symbolic
Module Procedures
public function umfpack_di_symbolic(n_row, n_col, Ap, Ai, Ax, Symbolic, Control, Info)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: n_row
integer, intent(in) :: n_col
integer, intent(in), target :: Ap(*)
integer, intent(in), target :: Ai(*)
real(kind=r8), intent(in), optional target :: Ax(*)
type(c_ptr), optional :: Symbolic
real(kind=r8), optional target :: Control(0:UMFPACK_CONTROL-1)
real(kind=r8), optional target :: Info(0:UMFPACK_INFO-1)
Return Value integer
public interface umfpack_zi_symbolic()
Arguments
None
public function umfpack_ci_symbolic(n_row, n_col, Ap, Ai, Ax, Symbolic, Control, Info)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: n_row
integer, intent(in) :: n_col
integer, intent(in), target :: Ap(*)
integer, intent(in), target :: Ai(*)
complex(kind=r8), intent(in), target :: Ax(*)
type(c_ptr), optional :: Symbolic
real(kind=r8), optional target :: Control(0:UMFPACK_CONTROL-1)
real(kind=r8), optional target :: Info(0:UMFPACK_INFO-1)
Return Value integer
Call graph
umfpack_symbolic calls umfpack_zi_symbolic, umfpack_di_symbolic, umfpack_ci_symbolic
umfpack_zi_symbolic calls umfpack_zi_symbolic, umfpack_ci_symbolic
umfpack_di_symbolic calls c_umfpack_di_symbolic
umfpack_ci_symbolic calls c_umfpack_zi_symbolic