umfpack_scale_function – MSOLV-fortran
umfpack_scale_function Interface
3 statements
Source File
public interface umfpack_scale_function
Calls
Called by
Contents
Module Procedures
umfpack_di_scale umfpack_zi_scale umfpack_ci_scale
Module Procedures
public function umfpack_di_scale(X, B, Numeric)
Arguments
Type Intent Optional Attributes Name
real(kind=r8), target :: X(*)
real(kind=r8), intent(in), target :: B(*)
type(c_ptr), intent(in), optional :: Numeric
Return Value integer
public interface umfpack_zi_scale()
Arguments
None
public function umfpack_ci_scale(Xx, Bx, Numeric)
Arguments
Type Intent Optional Attributes Name
complex(kind=r8), target :: Xx(*)
complex(kind=r8), intent(in), target :: Bx(*)
type(c_ptr), intent(in), optional :: Numeric
Return Value integer
Call graph
umfpack_scale_function calls umfpack_di_scale, umfpack_ci_scale, umfpack_zi_scale
umfpack_di_scale calls c_umfpack_di_scale
umfpack_ci_scale calls c_umfpack_zi_scale
umfpack_zi_scale calls umfpack_ci_scale, umfpack_zi_scale
umf4cscal_ip calls umfpack_scale_function
umf4scal_ip calls umfpack_scale_function
umf4scal calls umfpack_scale_function, umf4cscal_ip, umf4scal_ip, umf4zscal_ip, umf4scal
umf4cscal calls umfpack_scale_function, umf4cscal_ip, umf4cscal
umf4zscal_ip calls umfpack_scale_function
umf4zscal calls umfpack_scale_function, umf4cscal_ip, umf4zscal_ip, umf4zscal