umfpack_zi_solve – MSOLV-fortran
umfpack_zi_solve Interface
3 statements
Source File
public interface umfpack_zi_solve
Calls
Called by
Contents
Module Procedures
umfpack_zi_solve umfpack_ci_solve
Module Procedures
public interface umfpack_zi_solve()
Arguments
None
public function umfpack_ci_solve(sys, Ap, Ai, Ax, Xx, Bx, Numeric, Control, Info)
Arguments
Type Intent Optional Attributes Name
integer, intent(in), optional :: sys
integer, intent(in), optional target :: Ap(*)
integer, intent(in), optional target :: Ai(*)
complex(kind=r8), intent(in), optional target :: Ax(*)
complex(kind=r8), target :: Xx(*)
complex(kind=r8), intent(in), target :: Bx(*)
type(c_ptr), intent(in), optional :: Numeric
real(kind=r8), optional target :: Control(0:UMFPACK_CONTROL-1)
real(kind=r8), optional target :: Info(0:UMFPACK_INFO-1)
Return Value integer
Call graph
umfpack_zi_solve calls umfpack_zi_solve, umfpack_ci_solve
umfpack_ci_solve calls c_umfpack_zi_solve
umfpack_solve calls umfpack_zi_solve
s_umfpack_zi_solve calls umfpack_zi_solve